// Generated by mf2/cldr/generator/generate_plural_rules.py.
import Foundation

struct NumberOperands {
    let n: Double
    let i: Int64
    let v: Int64
    let w: Int64
    let f: Int64
    let t: Int64
    let e: Int64
    let c: Int64

    init?(_ value: String) {
        guard let parsed = Double(value), parsed.isFinite else { return nil }
        let n = abs(parsed)
        let normalized = value.trimmingCharacters(in: CharacterSet(charactersIn: "-+")).lowercased()
        let base = normalized.split(separator: "e", maxSplits: 1).first.map(String.init) ?? normalized
        let fraction = base.split(separator: ".", maxSplits: 1).dropFirst().first.map(String.init) ?? ""
        let fractionTrimmed = String(fraction.reversed().drop(while: { $0 == "0" }).reversed())
        self.n = n
        self.i = Int64(n.rounded(.towardZero))
        self.v = Int64(fraction.count)
        self.w = Int64(fractionTrimmed.count)
        self.f = Int64(fraction) ?? 0
        self.t = Int64(fractionTrimmed) ?? 0
        self.e = 0
        self.c = 0
    }

    fileprivate func operand(_ name: String) -> Int64 {
        switch name {
        case "i": i
        case "v": v
        case "w": w
        case "f": f
        case "t": t
        case "e": e
        case "c": c
        case "n": Int64(n.rounded(.towardZero))
        default: 0
        }
    }

    fileprivate func operandDouble(_ name: String) -> Double {
        if name == "n" { return n }
        return Double(operand(name))
    }
}

func selectCardinal(locale: String, operands: NumberOperands) -> String {
    switch lookupRuleId(locales: cardinalLocales, parents: cardinalParents, locale: locale) {
    case "r0": selectCardinalR0(operands)
    case "r1": selectCardinalR1(operands)
    case "r2": selectCardinalR2(operands)
    case "r3": selectCardinalR3(operands)
    case "r4": selectCardinalR4(operands)
    default: "other"
    }
}

func selectOrdinal(locale: String, operands: NumberOperands) -> String {
    switch lookupRuleId(locales: ordinalLocales, parents: ordinalParents, locale: locale) {
    case "r0": selectOrdinalR0(operands)
    case "r1": selectOrdinalR1(operands)
    case "r2": selectOrdinalR2(operands)
    default: "other"
    }
}

private let cardinalLocales: [String: String] = [
    "ar": "r3",
    "en": "r0",
    "fr": "r1",
    "ja": "r4",
    "ru": "r2",
]

private let ordinalLocales: [String: String] = [
    "ar": "r2",
    "en": "r0",
    "fr": "r1",
    "ja": "r2",
    "ru": "r2",
]

private let cardinalParents: [String: String] = [:]

private let ordinalParents: [String: String] = [:]

private func lookupRuleId(locales: [String: String], parents: [String: String], locale: String) -> String? {
    for candidate in pluralLookupChain(locale, parents: parents) {
        if let rule = locales[candidate] { return rule }
    }
    return nil
}

private func pluralLookupChain(_ locale: String, parents: [String: String]) -> [String] {
    var chain: [String] = []
    appendLookupChain(canonicalLocaleTag(locale), parents: parents, chain: &chain)
    return chain
}

private func appendLookupChain(_ locale: String, parents: [String: String], chain: inout [String]) {
    var current = locale
    while !current.isEmpty {
        if chain.contains(current) { return }
        chain.append(current)
        if let parent = parents[current] {
            appendLookupChain(parent, parents: parents, chain: &chain)
        }
        current = structuralParent(current) ?? ""
    }
}

private func canonicalLocaleTag(_ locale: String) -> String {
    let rawParts = locale.trimmingCharacters(in: .whitespacesAndNewlines)
        .replacingOccurrences(of: "_", with: "-")
        .split(separator: "-")
        .map(String.init)
    var parts: [String] = []
    for (index, part) in rawParts.enumerated() {
        if part.count == 1 { break }
        parts.append(canonicalSubtag(index: index, part: part))
    }
    return parts.joined(separator: "-")
}

private func canonicalSubtag(index: Int, part: String) -> String {
    if index == 0 { return part.lowercased() }
    if part.count == 4, part.allSatisfy(\.isLetter) {
        return part.prefix(1).uppercased() + part.dropFirst().lowercased()
    }
    if (part.count == 2 && part.allSatisfy(\.isLetter)) || (part.count == 3 && part.allSatisfy(\.isNumber)) {
        return part.uppercased()
    }
    return part.lowercased()
}

private func structuralParent(_ locale: String) -> String? {
    guard let index = locale.lastIndex(of: "-") else { return nil }
    return String(locale[..<index])
}

private func selectCardinalR0(_ operands: NumberOperands) -> String {
    if (((1 <= operands.operand("i") && operands.operand("i") <= 1)) && ((0 <= operands.operand("v") && operands.operand("v") <= 0))) { return "one" }
    return "other"
}

private func selectCardinalR1(_ operands: NumberOperands) -> String {
    if (((0 <= operands.operand("i") && operands.operand("i") <= 0) || (1 <= operands.operand("i") && operands.operand("i") <= 1))) { return "one" }
    if (((0 <= operands.operand("e") && operands.operand("e") <= 0)) && !((0 <= operands.operand("i") && operands.operand("i") <= 0)) && ((0 <= (operands.operand("i") % 1000000) && (operands.operand("i") % 1000000) <= 0)) && ((0 <= operands.operand("v") && operands.operand("v") <= 0))) || (!((0 <= operands.operand("e") && operands.operand("e") <= 5))) { return "many" }
    return "other"
}

private func selectCardinalR2(_ operands: NumberOperands) -> String {
    if (((0 <= operands.operand("v") && operands.operand("v") <= 0)) && ((1 <= (operands.operand("i") % 10) && (operands.operand("i") % 10) <= 1)) && !((11 <= (operands.operand("i") % 100) && (operands.operand("i") % 100) <= 11))) { return "one" }
    if (((0 <= operands.operand("v") && operands.operand("v") <= 0)) && ((2 <= (operands.operand("i") % 10) && (operands.operand("i") % 10) <= 4)) && !((12 <= (operands.operand("i") % 100) && (operands.operand("i") % 100) <= 14))) { return "few" }
    if (((0 <= operands.operand("v") && operands.operand("v") <= 0)) && ((0 <= (operands.operand("i") % 10) && (operands.operand("i") % 10) <= 0))) || (((0 <= operands.operand("v") && operands.operand("v") <= 0)) && ((5 <= (operands.operand("i") % 10) && (operands.operand("i") % 10) <= 9))) || (((0 <= operands.operand("v") && operands.operand("v") <= 0)) && ((11 <= (operands.operand("i") % 100) && (operands.operand("i") % 100) <= 14))) { return "many" }
    return "other"
}

private func selectCardinalR3(_ operands: NumberOperands) -> String {
    if (((operands.operandDouble("n").rounded(.towardZero) == operands.operandDouble("n") && 0.0 <= operands.operandDouble("n") && operands.operandDouble("n") <= 0.0))) { return "zero" }
    if (((operands.operandDouble("n").rounded(.towardZero) == operands.operandDouble("n") && 1.0 <= operands.operandDouble("n") && operands.operandDouble("n") <= 1.0))) { return "one" }
    if (((operands.operandDouble("n").rounded(.towardZero) == operands.operandDouble("n") && 2.0 <= operands.operandDouble("n") && operands.operandDouble("n") <= 2.0))) { return "two" }
    if ((((operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && 3.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) <= 10.0))) { return "few" }
    if ((((operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && 11.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) <= 99.0))) { return "many" }
    return "other"
}

private func selectCardinalR4(_ _: NumberOperands) -> String {
    return "other"
}

private func selectOrdinalR0(_ operands: NumberOperands) -> String {
    if ((((operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) && 1.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) <= 1.0)) && !(((operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && 11.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) <= 11.0))) { return "one" }
    if ((((operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) && 2.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) <= 2.0)) && !(((operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && 12.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) <= 12.0))) { return "two" }
    if ((((operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) && 3.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 10.0)) <= 3.0)) && !(((operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)).rounded(.towardZero) == (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && 13.0 <= (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) && (operands.operandDouble("n").truncatingRemainder(dividingBy: 100.0)) <= 13.0))) { return "few" }
    return "other"
}

private func selectOrdinalR1(_ operands: NumberOperands) -> String {
    if (((operands.operandDouble("n").rounded(.towardZero) == operands.operandDouble("n") && 1.0 <= operands.operandDouble("n") && operands.operandDouble("n") <= 1.0))) { return "one" }
    return "other"
}

private func selectOrdinalR2(_ _: NumberOperands) -> String {
    return "other"
}
