package com.box.l10n.mojito.queue;

import static org.assertj.core.api.Assertions.assertThat;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.atomic.AtomicInteger;
import javax.sql.DataSource;
import org.junit.Test;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.boot.test.util.TestPropertyValues;
import org.springframework.context.annotation.AdviceMode;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.TransactionDefinition;
import org.springframework.transaction.annotation.EnableTransactionManagement;
import org.springframework.transaction.support.DefaultTransactionStatus;

public class AsyncJobQueueJdbcTransactionConfigurationTest {

  @Test
  public void jdbcStoreBeanStartsTransactionsWithApplicationAspectjMode() {
    try (AnnotationConfigApplicationContext context = new AnnotationConfigApplicationContext()) {
      TestPropertyValues.of(
              "l10n.org.async-job-queue.enabled=true",
              "l10n.org.async-job-queue.store=jdbc",
              "l10n.org.async-job-queue.jdbc-dialect=hsql")
          .applyTo(context);
      context.register(
          AsyncJobQueueConfiguration.class,
          AsyncJobQueueProperties.class,
          AspectjTransactionTestConfig.class);
      context.refresh();

      AsyncJobStore asyncJobStore = context.getBean(AsyncJobStore.class);
      CountingDataSourceTransactionManager transactionManager =
          context.getBean(CountingDataSourceTransactionManager.class);

      AsyncJobId asyncJobId = asyncJobStore.enqueue("assetlocalize", "{}", Instant.EPOCH);
      List<AsyncJobRecord> claimedJobs =
          asyncJobStore.claimNextJobs("assetlocalize", 1, "worker", Duration.ofSeconds(30));
      assertThat(claimedJobs).hasSize(1);
      AsyncJobRecord claimedJob = claimedJobs.get(0);

      assertThat(claimedJob.id()).isEqualTo(asyncJobId);
      assertThat(
              asyncJobStore.markDone(
                  "assetlocalize", asyncJobId, "worker", claimedJob.leaseToken(), "{}"))
          .isTrue();

      assertThat(transactionManager.beginCount.get()).isGreaterThanOrEqualTo(3);
      assertThat(transactionManager.commitCount.get()).isGreaterThanOrEqualTo(3);
      assertThat(transactionManager.rollbackCount.get()).isZero();
    }
  }

  @Configuration
  @EnableTransactionManagement(mode = AdviceMode.ASPECTJ)
  @EnableConfigurationProperties(AsyncJobQueueProperties.class)
  static class AspectjTransactionTestConfig {

    @Bean
    DataSource dataSource() {
      DriverManagerDataSource dataSource = new DriverManagerDataSource();
      dataSource.setUrl(
          "jdbc:hsqldb:mem:async_job_queue_tx_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
      dataSource.setUsername("sa");
      dataSource.setPassword("");
      return dataSource;
    }

    @Bean
    NamedParameterJdbcTemplate namedParameterJdbcTemplate(DataSource dataSource) {
      return new NamedParameterJdbcTemplate(dataSource);
    }

    @Bean
    CountingDataSourceTransactionManager transactionManager(DataSource dataSource) {
      return new CountingDataSourceTransactionManager(dataSource);
    }

    @Bean
    Object createAsyncJobQueueSchema(DataSource dataSource) {
      JdbcTemplate jdbcTemplate = new JdbcTemplate(dataSource);
      jdbcTemplate.execute(
          """
          CREATE TABLE async_job_queue (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            queue_name VARCHAR(64) NOT NULL,
            status VARCHAR(16) NOT NULL,
            available_at TIMESTAMP(6) NOT NULL,
            lease_until TIMESTAMP(6) NULL,
            worker_id VARCHAR(128) NULL,
            lease_token VARCHAR(64) NULL,
            job_data LONGVARCHAR NOT NULL,
            attempt_count INTEGER DEFAULT 0 NOT NULL,
            last_error LONGVARCHAR NULL,
            created_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
            updated_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
          )
          """);
      return new Object();
    }
  }

  static class CountingDataSourceTransactionManager extends DataSourceTransactionManager {

    private final AtomicInteger beginCount = new AtomicInteger();
    private final AtomicInteger commitCount = new AtomicInteger();
    private final AtomicInteger rollbackCount = new AtomicInteger();

    CountingDataSourceTransactionManager(DataSource dataSource) {
      super(dataSource);
    }

    @Override
    protected void doBegin(Object transaction, TransactionDefinition definition) {
      beginCount.incrementAndGet();
      super.doBegin(transaction, definition);
    }

    @Override
    protected void doCommit(DefaultTransactionStatus status) {
      commitCount.incrementAndGet();
      super.doCommit(status);
    }

    @Override
    protected void doRollback(DefaultTransactionStatus status) {
      rollbackCount.incrementAndGet();
      super.doRollback(status);
    }
  }
}
