package com.box.l10n.mojito.queue;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.assertThrows;

import java.time.Duration;
import java.time.Instant;
import java.util.List;
import java.util.UUID;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

public class JdbcAsyncJobStoreTest {

  private static final String HSQL_CLAIM_NEXT_JOBS_SQL =
      """
      SELECT id
      FROM async_job_queue
      WHERE queue_name = :queueName
        AND (
          (status = :queuedStatus AND available_at <= :now)
          OR (status = :runningStatus AND lease_until <= :now)
        )
      ORDER BY available_at, id
      LIMIT :limit
      """;
  private static final String HSQL_CURRENT_TIMESTAMP_SQL = "VALUES CURRENT_TIMESTAMP";

  private JdbcTemplate jdbcTemplate;
  private JdbcAsyncJobStore jdbcAsyncJobStore;

  @Before
  public void setup() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.hsqldb.jdbc.JDBCDriver");
    dataSource.setUrl(
        "jdbc:hsqldb:mem:async_job_queue_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
    dataSource.setUsername("sa");
    dataSource.setPassword("");

    jdbcTemplate = new JdbcTemplate(dataSource);
    jdbcTemplate.execute(
        """
        CREATE TABLE async_job_queue (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          queue_name VARCHAR(64) NOT NULL,
          status VARCHAR(16) NOT NULL,
          available_at TIMESTAMP(6) NOT NULL,
          lease_until TIMESTAMP(6) NULL,
          worker_id VARCHAR(128) NULL,
          lease_token VARCHAR(64) NULL,
          job_data LONGVARCHAR NOT NULL,
          attempt_count INTEGER DEFAULT 0 NOT NULL,
          last_error LONGVARCHAR NULL,
          created_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
          updated_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL
        )
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_AVAILABLE_ID
          ON async_job_queue (queue_name, status, available_at, id)
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_LEASE_ID
          ON async_job_queue (queue_name, status, lease_until, id)
        """);
    jdbcAsyncJobStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(dataSource),
            HSQL_CLAIM_NEXT_JOBS_SQL,
            HSQL_CURRENT_TIMESTAMP_SQL);
  }

  @After
  public void tearDown() {
    jdbcTemplate.execute("DROP TABLE async_job_queue IF EXISTS");
  }

  @Test
  public void enqueueAndClaimFiltersByQueueAvailabilityAndOrder() {
    Instant now = Instant.now();
    AsyncJobId firstReadyId =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"first\"}", now.minusSeconds(2));
    jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"later\"}", now.plusSeconds(30));
    jdbcAsyncJobStore.enqueue("stats", "{\"name\":\"other-queue\"}", now.minusSeconds(3));
    AsyncJobId secondReadyId =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"second\"}", now.minusSeconds(1));

    List<AsyncJobRecord> claimed =
        jdbcAsyncJobStore.claimNextJobs("assetlocalize", 10, "worker-a", Duration.ofSeconds(10));

    assertThat(claimed).hasSize(2);
    assertThat(claimed.get(0).id()).isEqualTo(firstReadyId);
    assertThat(claimed.get(1).id()).isEqualTo(secondReadyId);
    assertThat(claimed).allMatch(job -> job.status() == AsyncJobStatus.RUNNING);
    assertThat(claimed).allMatch(job -> "worker-a".equals(job.workerId()));
    assertThat(claimed).allMatch(job -> job.attemptCount() == 1);
    assertThat(claimed).allMatch(job -> job.leaseToken() != null && !job.leaseToken().isBlank());
    assertThat(claimed).allMatch(job -> job.leaseUntil().isAfter(job.updatedDate()));

    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactlyInAnyOrder(
            new AsyncJobStatusCount(AsyncJobStatus.RUNNING, 2),
            new AsyncJobStatusCount(AsyncJobStatus.QUEUED, 1));
  }

  @Test
  public void leaseFencingRejectsWrongOwnerTokenAndExpiredOwner() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofMillis(50))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.heartbeat(
                "assetlocalize", id, "worker-a", "wrong-token", Duration.ofSeconds(1)))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-b", claimed.leaseToken(), "{\"v\":2}"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-b",
                claimed.leaseToken(),
                Instant.now(),
                "{\"v\":2}",
                "wrong owner"))
        .isFalse();

    Thread.sleep(80);
    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), "{\"v\":2}"))
        .isFalse();

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(1))
            .get(0);
    assertThat(reclaimed.id()).isEqualTo(id);
    assertThat(reclaimed.workerId()).isEqualTo("worker-b");
    assertThat(reclaimed.leaseToken()).isNotEqualTo(claimed.leaseToken());
    assertThat(reclaimed.attemptCount()).isEqualTo(2);
  }

  @Test
  public void requeuePersistsErrorAndMarkDoneClearsLeaseAndError() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);

    Instant nextAvailableAt = Instant.now().plusMillis(50);
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                nextAvailableAt,
                "{\"step\":\"requeued\"}",
                "temporary failure"))
        .isTrue();
    assertThat(
            jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(1)))
        .isEmpty();

    Thread.sleep(80);
    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(reclaimed.jobData()).isEqualTo("{\"step\":\"requeued\"}");
    assertThat(reclaimed.lastError()).isEqualTo("temporary failure");
    assertThat(reclaimed.attemptCount()).isEqualTo(2);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", reclaimed.leaseToken(), "{\"step\":\"done\"}"))
        .isTrue();

    AsyncJobRecord done = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(done.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(done.jobData()).isEqualTo("{\"step\":\"done\"}");
    assertThat(done.lastError()).isNull();
    assertThat(done.workerId()).isNull();
    assertThat(done.leaseToken()).isNull();
    assertThat(done.leaseUntil()).isNull();
  }

  @Test
  public void markFailedPersistsTerminalStateAndPreventsReclaim() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                "{\"step\":\"failed\"}",
                "boom"))
        .isTrue();

    AsyncJobRecord failed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(failed.status()).isEqualTo(AsyncJobStatus.FAILED);
    assertThat(failed.jobData()).isEqualTo("{\"step\":\"failed\"}");
    assertThat(failed.lastError()).isEqualTo("boom");
    assertThat(failed.workerId()).isNull();
    assertThat(failed.leaseToken()).isNull();
    assertThat(failed.leaseUntil()).isNull();
    assertThat(
            jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(1)))
        .isEmpty();
    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactly(new AsyncJobStatusCount(AsyncJobStatus.FAILED, 1));
  }

  @Test
  public void invalidNumericIdsFailFast() {
    assertThrows(
        IllegalArgumentException.class,
        () -> jdbcAsyncJobStore.getByIds(List.of(new AsyncJobId("abc"))));
  }
}
