package com.box.l10n.mojito.queue;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.assertThrows;
import static org.mockito.AdditionalAnswers.delegatesTo;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.inOrder;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoMoreInteractions;

import io.micrometer.core.instrument.Tags;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.time.LocalDateTime;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.time.temporal.ChronoUnit;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.concurrent.atomic.AtomicReference;
import javax.sql.DataSource;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.transaction.support.TransactionSynchronizationManager;

public class JdbcAsyncJobStoreTest {

  private JdbcTemplate jdbcTemplate;
  private JdbcAsyncJobStore jdbcAsyncJobStore;

  @Before
  public void setup() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.hsqldb.jdbc.JDBCDriver");
    dataSource.setUrl(
        "jdbc:hsqldb:mem:async_job_queue_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
    dataSource.setUsername("sa");
    dataSource.setPassword("");

    jdbcTemplate = new JdbcTemplate(dataSource);
    jdbcTemplate.execute(
        """
        CREATE TABLE async_job_queue (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY(START WITH 1) PRIMARY KEY,
          queue_name VARCHAR(64) NOT NULL,
          status VARCHAR(16) NOT NULL,
          available_at TIMESTAMP(6) NOT NULL,
          lease_until TIMESTAMP(6) NULL,
          worker_id VARCHAR(128) NULL,
          lease_token VARCHAR(64) NULL,
          job_data LONGVARCHAR NOT NULL,
          attempt_count INTEGER DEFAULT 0 NOT NULL,
          last_error LONGVARCHAR NULL,
          created_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
          updated_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT C_ASYNC_JOB_QUEUE_ID_POSITIVE
            CHECK (id > 0),
          CONSTRAINT C_ASYNC_JOB_QUEUE_STATUS
            CHECK (status IN ('queued', 'running', 'done', 'failed')),
          CONSTRAINT C_ASYNC_JOB_QUEUE_ATTEMPT_RANGE
            CHECK (attempt_count BETWEEN 0 AND 101),
          CONSTRAINT C_ASYNC_JOB_QUEUE_JOB_DATA_LENGTH
            CHECK (CHAR_LENGTH(job_data) <= 1000000),
          CONSTRAINT C_ASYNC_JOB_QUEUE_LAST_ERROR_LENGTH
            CHECK (last_error IS NULL OR CHAR_LENGTH(last_error) <= 4000),
          CONSTRAINT C_ASYNC_JOB_QUEUE_FAILED_LAST_ERROR
            CHECK (status <> 'failed' OR (last_error IS NOT NULL AND TRIM(last_error) <> '')),
          CONSTRAINT C_ASYNC_JOB_QUEUE_DONE_LAST_ERROR
            CHECK (status <> 'done' OR last_error IS NULL),
          CONSTRAINT C_ASYNC_JOB_QUEUE_RUNNING_LEASE_OWNER
            CHECK (
              (status = 'running' AND lease_until IS NOT NULL AND worker_id IS NOT NULL AND lease_token IS NOT NULL)
              OR (status <> 'running' AND lease_until IS NULL AND worker_id IS NULL AND lease_token IS NULL)
            ),
          CONSTRAINT C_ASYNC_JOB_QUEUE_LEASE_OWNER_NONBLANK
            CHECK (
              status <> 'running'
              OR (TRIM(worker_id) <> '' AND TRIM(lease_token) <> '')
            )
        )
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_AVAILABLE_ID
          ON async_job_queue (queue_name, status, available_at, id)
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_LEASE_ID
          ON async_job_queue (queue_name, status, lease_until, id)
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_UPDATED_ID
          ON async_job_queue (queue_name, status, updated_date, id)
        """);
    jdbcAsyncJobStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(dataSource), AsyncJobQueueJdbcDialect.HSQL);
  }

  @After
  public void tearDown() {
    jdbcTemplate.execute("DROP TABLE async_job_queue IF EXISTS");
  }

  @Test
  public void scheduledRetentionPreservesAgeWhenDatabaseClockIsBehindHost() {
    assertScheduledRetentionUsesDatabaseClock(Duration.ofDays(-365));
  }

  @Test
  public void scheduledRetentionPreservesAgeWhenDatabaseClockIsAheadOfHost() {
    assertScheduledRetentionUsesDatabaseClock(Duration.ofDays(365));
  }

  private void assertScheduledRetentionUsesDatabaseClock(Duration clockOffset) {
    // Keep seconds at zero: LocalDateTime.toString() omits them, unlike an SQL timestamp literal.
    Instant databaseNow = Instant.now().truncatedTo(ChronoUnit.MINUTES).plus(clockOffset);
    JdbcAsyncJobStore store =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate),
            AsyncJobQueueJdbcDialect.HSQL,
            "VALUES TIMESTAMP '"
                + LocalDateTime.ofInstant(databaseNow, ZoneOffset.UTC)
                    .format(DateTimeFormatter.ofPattern("uuuu-MM-dd HH:mm:ss"))
                + "'");
    AsyncJobId fresh = store.enqueueNow("assetlocalize", "fresh");
    AsyncJobId expired = store.enqueueNow("assetlocalize", "expired");
    List<AsyncJobRecord> claimed =
        store.claimNextJobs("assetlocalize", 2, "worker", Duration.ofMinutes(1));
    for (AsyncJobRecord job : claimed) {
      assertThat(store.markDone("assetlocalize", job.id(), "worker", job.leaseToken(), null))
          .isTrue();
    }
    jdbcTemplate.update(
        "UPDATE async_job_queue SET updated_date = ? WHERE id = ?",
        LocalDateTime.ofInstant(databaseNow.minus(Duration.ofDays(2)), ZoneOffset.UTC),
        Long.parseLong(expired.value()));
    AsyncJobRecord freshBefore = store.getByIds(List.of(fresh)).get(0);
    AsyncJobQueueProperties properties = new AsyncJobQueueProperties();
    properties.getQueues().put("assetlocalize", new AsyncJobQueueProperties.QueueSettings());
    properties.getRetention().setDoneRetentionMs(Duration.ofDays(1).toMillis());
    SimpleMeterRegistry registry = new SimpleMeterRegistry();
    try {
      new AsyncJobQueueRetentionCleaner(store, properties, List.of(), registry)
          .cleanupTerminalJobs();
      assertThat(store.getByIds(List.of(fresh, expired))).containsExactly(freshBefore);
    } finally {
      registry.close();
    }
  }

  @Test
  public void relativeRetentionUsesStrictCutoffAndBoundedTerminalQueueScope() {
    Instant databaseNow = Instant.parse("2030-01-02T00:00:00Z");
    JdbcAsyncJobStore store =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate),
            AsyncJobQueueJdbcDialect.HSQL,
            "VALUES TIMESTAMP '2030-01-02 00:00:00'");
    for (AsyncJobStatus status : List.of(AsyncJobStatus.DONE, AsyncJobStatus.FAILED)) {
      List<AsyncJobId> ids = new ArrayList<>();
      for (int i = 0; i < 5; i++) {
        ids.add(store.enqueueNow("assetlocalize", "{}"));
      }
      for (AsyncJobRecord job :
          store.claimNextJobs("assetlocalize", 5, "worker", Duration.ofMinutes(1))) {
        assertThat(
                status == AsyncJobStatus.DONE
                    ? store.markDone("assetlocalize", job.id(), "worker", job.leaseToken(), null)
                    : store.markFailed(
                        "assetlocalize", job.id(), "worker", job.leaseToken(), null, "failed"))
            .isTrue();
      }
      Instant cutoff = databaseNow.minus(Duration.ofDays(1));
      for (int i = 0; i < 4; i++) {
        jdbcTemplate.update(
            "UPDATE async_job_queue SET updated_date = ? WHERE id = ?",
            LocalDateTime.ofInstant(cutoff.plusNanos((i - 2L) * 1_000), ZoneOffset.UTC),
            Long.parseLong(ids.get(i).value()));
      }
      List<AsyncJobRecord> retained = store.getByIds(ids.subList(2, 5));
      assertThat(store.deleteTerminalJobsOlderThan("other", status, Duration.ofDays(1), 100))
          .isZero();
      assertThat(store.deleteTerminalJobsOlderThan("assetlocalize", status, Duration.ofDays(1), 1))
          .isEqualTo(1);
      assertThat(store.getByIds(ids)).hasSize(4);
      assertThat(store.getByIds(List.of(ids.get(0)))).isEmpty();
      assertThat(
              store.deleteTerminalJobsOlderThan("assetlocalize", status, Duration.ofDays(1), 100))
          .isEqualTo(1);
      assertThat(store.getByIds(ids)).containsExactlyElementsOf(retained);
    }
  }

  @Test
  public void scheduledRetentionKeepsCommittedBatchesWhenDeletionCountersConflict() {
    DataSource dataSource = jdbcTemplate.getDataSource();
    JdbcAsyncJobStore store =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(dataSource),
            AsyncJobQueueJdbcDialect.HSQL,
            new DataSourceTransactionManager(dataSource));
    AsyncJobQueueProperties properties = new AsyncJobQueueProperties();
    properties.getRetention().setBatchSize(1);
    List<AsyncJobId> firstBatch = new ArrayList<>();
    List<AsyncJobId> secondBatch = new ArrayList<>();
    List<AsyncJobId> protectedIds = new ArrayList<>();
    SimpleMeterRegistry registry = new SimpleMeterRegistry();
    try {
      for (String queue : List.of("assetlocalize", "later")) {
        properties.getQueues().put(queue, new AsyncJobQueueProperties.QueueSettings());
        for (AsyncJobStatus status : List.of(AsyncJobStatus.DONE, AsyncJobStatus.FAILED)) {
          firstBatch.add(retentionRow(store, queue, status, true));
          secondBatch.add(retentionRow(store, queue, status, true));
          protectedIds.add(retentionRow(store, queue, status, false));
          registry.gauge(
              "asyncJobQueue.retention.deleted",
              Tags.of("queueName", queue, "status", status.getDatabaseValue()),
              1);
        }
        AsyncJobId running = store.enqueueNow(queue, "running");
        assertThat(store.claimNextJobs(queue, 1, "worker", Duration.ofMinutes(1)))
            .extracting(AsyncJobRecord::id)
            .containsExactly(running);
        protectedIds.add(running);
        protectedIds.add(store.enqueueNow(queue, "queued"));
      }
      List<AsyncJobRecord> protectedRows = store.getByIds(protectedIds);
      List<AsyncJobRecord> nextRows = store.getByIds(secondBatch);
      var cleaner = new AsyncJobQueueRetentionCleaner(store, properties, List.of(), registry);

      cleaner.cleanupTerminalJobs();

      assertThat(store.getByIds(firstBatch)).isEmpty();
      assertThat(store.getByIds(secondBatch)).containsExactlyElementsOf(nextRows);
      assertThat(store.getByIds(protectedIds)).containsExactlyElementsOf(protectedRows);
      assertThat(registry.find("asyncJobQueue.retention.failed").meters()).isEmpty();
      assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isFalse();
      assertThat(TransactionSynchronizationManager.getResourceMap()).isEmpty();

      cleaner.cleanupTerminalJobs();

      assertThat(store.getByIds(secondBatch)).isEmpty();
      assertThat(store.getByIds(protectedIds)).containsExactlyElementsOf(protectedRows);
      assertThat(registry.find("asyncJobQueue.retention.failed").meters()).isEmpty();
    } finally {
      registry.close();
    }
  }

  private AsyncJobId retentionRow(
      JdbcAsyncJobStore store, String queue, AsyncJobStatus status, boolean old) {
    AsyncJobId id = store.enqueueNow(queue, "retained payload");
    AsyncJobRecord claimed =
        store.claimNextJobs(queue, 1, "worker", Duration.ofMinutes(1)).getFirst();
    assertThat(claimed.id()).isEqualTo(id);
    assertThat(
            status == AsyncJobStatus.DONE
                ? store.markDone(queue, id, "worker", claimed.leaseToken(), null)
                : store.markFailed(queue, id, "worker", claimed.leaseToken(), null, "failure"))
        .isTrue();
    if (old) {
      jdbcTemplate.update(
          "UPDATE async_job_queue SET updated_date = TIMESTAMP '2000-01-01 00:00:00' WHERE id = ?",
          Long.parseLong(id.value()));
    }
    return id;
  }

  @Test
  public void retentionDoesNotRepeatCommittedDeleteAfterLostAcknowledgementAndFailedDiagnostics() {
    AsyncJobId first = completedRetentionCandidate();
    AsyncJobId second = completedRetentionCandidate();
    AsyncJobRecord secondBefore = jdbcAsyncJobStore.getByIds(List.of(second)).getFirst();
    DataSource dataSource = jdbcTemplate.getDataSource();
    JdbcAsyncJobStore committed =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(dataSource),
            AsyncJobQueueJdbcDialect.HSQL,
            new DataSourceTransactionManager(dataSource));
    AsyncJobStore uncertain = mock(AsyncJobStore.class, delegatesTo(committed));
    doAnswer(
            invocation -> {
              assertThat(
                      committed.deleteTerminalJobsOlderThan(
                          "assetlocalize", AsyncJobStatus.DONE, Duration.ofDays(7), 1))
                  .isEqualTo(1);
              assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isFalse();
              throw new IllegalStateException("acknowledgement lost after committed DELETE");
            })
        .when(uncertain)
        .deleteTerminalJobsOlderThan("assetlocalize", AsyncJobStatus.DONE, Duration.ofDays(7), 1);
    var properties = new AsyncJobQueueProperties();
    properties.getQueues().put("assetlocalize", new AsyncJobQueueProperties.QueueSettings());
    properties.getRetention().setBatchSize(1);
    var registry = new SimpleMeterRegistry();
    try {
      registry.gauge(
          "asyncJobQueue.retention.failed",
          Tags.of("queueName", "assetlocalize", "status", "done"),
          1);

      new AsyncJobQueueRetentionCleaner(uncertain, properties, List.of(), registry)
          .cleanupTerminalJobs();

      assertThat(committed.getByIds(List.of(first))).isEmpty();
      assertThat(committed.getByIds(List.of(second))).containsExactly(secondBefore);
      verify(uncertain)
          .deleteTerminalJobsOlderThan("assetlocalize", AsyncJobStatus.DONE, Duration.ofDays(7), 1);
      verify(uncertain)
          .deleteTerminalJobsOlderThan(
              "assetlocalize", AsyncJobStatus.FAILED, Duration.ofDays(30), 1);
      verifyNoMoreInteractions(uncertain);
      assertThat(registry.find("asyncJobQueue.retention.deleted").meters()).isEmpty();
      assertThat(TransactionSynchronizationManager.getResourceMap()).isEmpty();
    } finally {
      registry.close();
    }
  }

  @Test
  public void relativeRetentionRejectsInvalidInputsBeforeReadingClock() {
    JdbcAsyncJobStore store = storeWithBrokenDatabaseClock();
    for (Duration age :
        List.of(
            Duration.ZERO,
            Duration.ofNanos(-1),
            Duration.ofDays(366),
            Duration.ofSeconds(Long.MAX_VALUE))) {
      assertThrows(
          IllegalArgumentException.class,
          () -> store.deleteTerminalJobsOlderThan("assetlocalize", AsyncJobStatus.DONE, age, 1));
    }
    assertThrows(
        NullPointerException.class,
        () -> store.deleteTerminalJobsOlderThan("assetlocalize", AsyncJobStatus.DONE, null, 1));
    for (AsyncJobStatus status : List.of(AsyncJobStatus.QUEUED, AsyncJobStatus.RUNNING)) {
      assertThrows(
          IllegalArgumentException.class,
          () -> store.deleteTerminalJobsOlderThan("assetlocalize", status, Duration.ofDays(1), 1));
    }
    assertThrows(
        IllegalArgumentException.class,
        () -> store.deleteTerminalJobsOlderThan(" ", AsyncJobStatus.DONE, Duration.ofDays(1), 1));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            store.deleteTerminalJobsOlderThan(
                "assetlocalize", AsyncJobStatus.DONE, Duration.ofDays(1), 1001));
    assertThat(store.deleteTerminalJobsOlderThan(null, null, null, 0)).isZero();
  }

  @Test
  public void relativeRetentionCannotDeleteWhenClockFailsOrCutoffUnderflows() {
    AsyncJobId id = completedRetentionCandidate();
    AsyncJobRecord before = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    for (String clockSql :
        List.of("VALUES CAST(NULL AS TIMESTAMP)", "VALUES TIMESTAMP '1970-01-01 00:00:00'")) {
      JdbcAsyncJobStore store =
          new JdbcAsyncJobStore(
              new NamedParameterJdbcTemplate(jdbcTemplate),
              AsyncJobQueueJdbcDialect.HSQL,
              clockSql);
      assertThrows(
          RuntimeException.class,
          () ->
              store.deleteTerminalJobsOlderThan(
                  "assetlocalize", AsyncJobStatus.DONE, Duration.ofDays(1), 100));
      assertThat(jdbcAsyncJobStore.getByIds(List.of(id))).containsExactly(before);
    }
  }

  @Test
  public void relativeRetentionClockAndDeleteShareTransactionAndRollbackTogether() {
    AsyncJobId id = completedRetentionCandidate();
    AsyncJobRecord before = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    DataSource dataSource = jdbcTemplate.getDataSource();
    List<Object> connectionHolders = new ArrayList<>();
    NamedParameterJdbcTemplate observingJdbc =
        new NamedParameterJdbcTemplate(dataSource) {
          @Override
          public <T> T queryForObject(String sql, SqlParameterSource params, RowMapper<T> mapper) {
            assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isTrue();
            connectionHolders.add(TransactionSynchronizationManager.getResource(dataSource));
            return super.queryForObject(sql, params, mapper);
          }

          @Override
          public int update(String sql, SqlParameterSource params) {
            assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isTrue();
            assertThat(TransactionSynchronizationManager.getCurrentTransactionIsolationLevel())
                .isEqualTo(JdbcAsyncJobStore.TRANSACTION_ISOLATION_LEVEL);
            connectionHolders.add(TransactionSynchronizationManager.getResource(dataSource));
            assertThat(super.update(sql, params)).isEqualTo(1);
            throw new IllegalStateException("failure after DELETE before commit");
          }
        };
    JdbcAsyncJobStore store =
        new JdbcAsyncJobStore(
            observingJdbc,
            AsyncJobQueueJdbcDialect.HSQL,
            new DataSourceTransactionManager(dataSource));
    assertThrows(
        IllegalStateException.class,
        () ->
            store.deleteTerminalJobsOlderThan(
                "assetlocalize", AsyncJobStatus.DONE, Duration.ofDays(1), 100));
    assertThat(connectionHolders).hasSize(2).doesNotContainNull();
    assertThat(connectionHolders.get(0)).isSameAs(connectionHolders.get(1));
    assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isFalse();
    assertThat(jdbcAsyncJobStore.getByIds(List.of(id))).containsExactly(before);
  }

  private AsyncJobId completedRetentionCandidate() {
    AsyncJobId id = jdbcAsyncJobStore.enqueueNow("assetlocalize", "{}");
    AsyncJobRecord job =
        jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker", Duration.ofMinutes(1)).get(0);
    assertThat(jdbcAsyncJobStore.markDone("assetlocalize", id, "worker", job.leaseToken(), null))
        .isTrue();
    jdbcTemplate.update(
        "UPDATE async_job_queue SET updated_date = TIMESTAMP '2000-01-01 00:00:00' WHERE id = ?",
        Long.parseLong(id.value()));
    return id;
  }

  @Test
  public void enqueueAndClaimFiltersByQueueAvailabilityAndOrder() {
    Instant now = Instant.now();
    AsyncJobId firstReadyId =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"first\"}", now.minusSeconds(2));
    jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"later\"}", now.plusSeconds(30));
    jdbcAsyncJobStore.enqueue("stats", "{\"name\":\"other-queue\"}", now.minusSeconds(3));
    AsyncJobId secondReadyId =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"second\"}", now.minusSeconds(1));

    List<AsyncJobRecord> claimed =
        jdbcAsyncJobStore.claimNextJobs("assetlocalize", 10, "worker-a", Duration.ofSeconds(10));

    assertThat(claimed).hasSize(2);
    assertThat(claimed.get(0).id()).isEqualTo(firstReadyId);
    assertThat(claimed.get(1).id()).isEqualTo(secondReadyId);
    assertThat(claimed).allMatch(job -> job.status() == AsyncJobStatus.RUNNING);
    assertThat(claimed).allMatch(job -> "worker-a".equals(job.workerId()));
    assertThat(claimed).allMatch(job -> job.attemptCount() == 1);
    assertThat(claimed).allMatch(job -> job.leaseToken() != null && !job.leaseToken().isBlank());
    assertThat(claimed).allMatch(job -> job.leaseUntil().isAfter(job.updatedDate()));
    assertThat(claimed).allMatch(job -> !job.leaseReclaimed());

    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactlyInAnyOrder(
            new AsyncJobStatusCount(AsyncJobStatus.RUNNING, 2),
            new AsyncJobStatusCount(AsyncJobStatus.QUEUED, 1));
  }

  @Test
  public void leaseFencingRejectsWrongOwnerTokenAndExpiredOwner() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofMillis(50))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.heartbeat(
                "assetlocalize", id, "worker-a", "wrong-token", Duration.ofSeconds(1)))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-b", claimed.leaseToken(), "{\"v\":2}"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-b",
                claimed.leaseToken(),
                Instant.now(),
                "{\"v\":2}",
                "wrong owner"))
        .isFalse();

    Thread.sleep(80);
    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), "{\"v\":2}"))
        .isFalse();

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(1))
            .get(0);
    assertThat(reclaimed.id()).isEqualTo(id);
    assertThat(reclaimed.workerId()).isEqualTo("worker-b");
    assertThat(reclaimed.leaseToken()).isNotEqualTo(claimed.leaseToken());
    assertThat(reclaimed.attemptCount()).isEqualTo(2);
    assertThat(reclaimed.leaseReclaimed()).isTrue();
  }

  @Test
  public void reclaimedLeaseFencesStaleOwnerTransitions() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    AsyncJobRecord firstClaim =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofMillis(50))
            .get(0);

    Thread.sleep(80);

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(5))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", firstClaim.leaseToken(), "{\"v\":\"stale\"}"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                firstClaim.leaseToken(),
                Instant.now().plusSeconds(1),
                "{\"v\":\"stale\"}",
                "stale requeue"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize", id, "worker-a", firstClaim.leaseToken(), null, "stale failure"))
        .isFalse();

    AsyncJobRecord running = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(running.status()).isEqualTo(AsyncJobStatus.RUNNING);
    assertThat(running.workerId()).isEqualTo("worker-b");
    assertThat(running.leaseToken()).isEqualTo(reclaimed.leaseToken());
    assertThat(running.attemptCount()).isEqualTo(2);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-b", reclaimed.leaseToken(), "{\"v\":\"done\"}"))
        .isTrue();
    AsyncJobRecord done = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(done.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(done.jobData()).isEqualTo("{\"v\":\"done\"}");
    assertThat(done.lastError()).isNull();
  }

  @Test
  public void claimUpdateRechecksClaimableStateAfterCandidateSelection() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    JdbcAsyncJobStore racingStore =
        new JdbcAsyncJobStore(
            new ClaimRaceNamedParameterJdbcTemplate(
                jdbcTemplate.getDataSource(),
                id,
                """
                UPDATE async_job_queue
                SET status = 'done', updated_date = CURRENT_TIMESTAMP
                WHERE id = ?
                """),
            AsyncJobQueueJdbcDialect.HSQL);

    List<AsyncJobRecord> claimed =
        racingStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5));

    assertThat(claimed).isEmpty();
    AsyncJobRecord changedJob = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(changedJob.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(changedJob.attemptCount()).isZero();
    assertThat(changedJob.workerId()).isNull();
    assertThat(changedJob.leaseToken()).isNull();
    assertThat(changedJob.leaseUntil()).isNull();
  }

  @Test
  public void claimUpdateRequiresSelectedStateAfterCandidateSelection() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    JdbcAsyncJobStore racingStore =
        new JdbcAsyncJobStore(
            new ClaimRaceNamedParameterJdbcTemplate(
                jdbcTemplate.getDataSource(),
                id,
                """
                UPDATE async_job_queue
                SET
                  status = 'running',
                  lease_until = TIMESTAMP '2000-01-01 00:00:00',
                  worker_id = 'other-worker',
                  lease_token = 'other-token',
                  updated_date = CURRENT_TIMESTAMP
                WHERE id = ?
                """),
            AsyncJobQueueJdbcDialect.HSQL);

    List<AsyncJobRecord> claimed =
        racingStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5));

    assertThat(claimed).isEmpty();
    AsyncJobRecord changedJob = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(changedJob.status()).isEqualTo(AsyncJobStatus.RUNNING);
    assertThat(changedJob.attemptCount()).isZero();
    assertThat(changedJob.workerId()).isEqualTo("other-worker");
    assertThat(changedJob.leaseToken()).isEqualTo("other-token");
    assertThat(changedJob.leaseUntil()).isBefore(Instant.now());
  }

  @Test
  public void claimReadbackInvariantRollsBackClaimInTransaction() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    DataSource dataSource = jdbcTemplate.getDataSource();
    JdbcAsyncJobStore missingReadbackStore =
        new JdbcAsyncJobStore(
            new ClaimReadbackDroppingNamedParameterJdbcTemplate(dataSource),
            AsyncJobQueueJdbcDialect.HSQL,
            new DataSourceTransactionManager(dataSource));

    IllegalStateException exception =
        assertThrows(
            IllegalStateException.class,
            () ->
                missingReadbackStore.claimNextJobs(
                    "assetlocalize", 1, "worker-a", Duration.ofSeconds(5)));

    assertThat(exception)
        .hasMessageContaining("claim readback missing claimed job")
        .hasMessageContaining(id.value());
    AsyncJobRecord rolledBackJob = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(rolledBackJob.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(rolledBackJob.attemptCount()).isZero();
    assertThat(rolledBackJob.workerId()).isNull();
    assertThat(rolledBackJob.leaseToken()).isNull();
    assertThat(rolledBackJob.leaseUntil()).isNull();
  }

  @Test
  public void concurrentClaimsCompleteEachJobOnce() throws Exception {
    String queueName = "assetlocalize";
    int jobCount = 80;
    int workerCount = 6;
    int batchSize = 3;
    for (int i = 0; i < jobCount; i++) {
      jdbcAsyncJobStore.enqueue(queueName, "{\"id\":" + i + "}", Instant.now().minusSeconds(1));
    }

    Set<AsyncJobId> claimedIds = ConcurrentHashMap.newKeySet();
    AtomicBoolean stop = new AtomicBoolean();
    CountDownLatch start = new CountDownLatch(1);
    ExecutorService executorService = Executors.newFixedThreadPool(workerCount);
    List<Future<Integer>> futures = new ArrayList<>();
    try {
      for (int workerIndex = 0; workerIndex < workerCount; workerIndex++) {
        String workerId = "worker-" + workerIndex;
        futures.add(
            executorService.submit(
                () -> {
                  start.await();
                  int processed = 0;
                  try {
                    while (!stop.get() && statusCount(queueName, AsyncJobStatus.DONE) < jobCount) {
                      List<AsyncJobRecord> claimed =
                          jdbcAsyncJobStore.claimNextJobs(
                              queueName, batchSize, workerId, Duration.ofSeconds(30));
                      if (claimed.isEmpty()) {
                        Thread.sleep(5);
                        continue;
                      }

                      for (AsyncJobRecord job : claimed) {
                        assertThat(claimedIds.add(job.id()))
                            .as("job should only be claimed once: %s", job.id())
                            .isTrue();
                        assertThat(
                                jdbcAsyncJobStore.markDone(
                                    queueName,
                                    job.id(),
                                    workerId,
                                    job.leaseToken(),
                                    "{\"done\":" + job.id().value() + "}"))
                            .isTrue();
                        processed++;
                      }
                    }
                    return processed;
                  } catch (Throwable throwable) {
                    stop.set(true);
                    throw throwable;
                  }
                }));
      }

      start.countDown();
      int processed = 0;
      for (Future<Integer> future : futures) {
        processed += future.get(30, TimeUnit.SECONDS);
      }

      assertThat(processed).isEqualTo(jobCount);
      assertThat(claimedIds).hasSize(jobCount);
      assertThat(statusCount(queueName, AsyncJobStatus.DONE)).isEqualTo(jobCount);
      assertThat(statusCount(queueName, AsyncJobStatus.QUEUED)).isZero();
      assertThat(statusCount(queueName, AsyncJobStatus.RUNNING)).isZero();
      assertThat(statusCount(queueName, AsyncJobStatus.FAILED)).isZero();
    } finally {
      stop.set(true);
      executorService.shutdownNow();
      assertThat(executorService.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
    }
  }

  @Test
  public void concurrentClaimsCanRequeueAndCompleteEachJobOnce() throws Exception {
    String queueName = "assetlocalize";
    int jobCount = 60;
    int workerCount = 6;
    int batchSize = 3;
    for (int i = 0; i < jobCount; i++) {
      jdbcAsyncJobStore.enqueue(queueName, "{\"id\":" + i + "}", Instant.now().minusSeconds(1));
    }

    ConcurrentHashMap<AsyncJobId, AtomicInteger> claimsById = new ConcurrentHashMap<>();
    Set<AsyncJobId> completedIds = ConcurrentHashMap.newKeySet();
    AtomicBoolean stop = new AtomicBoolean();
    CountDownLatch start = new CountDownLatch(1);
    ExecutorService executorService = Executors.newFixedThreadPool(workerCount);
    List<Future<Integer>> futures = new ArrayList<>();
    try {
      for (int workerIndex = 0; workerIndex < workerCount; workerIndex++) {
        String workerId = "worker-" + workerIndex;
        futures.add(
            executorService.submit(
                () -> {
                  start.await();
                  int completed = 0;
                  try {
                    while (!stop.get() && statusCount(queueName, AsyncJobStatus.DONE) < jobCount) {
                      List<AsyncJobRecord> claimed =
                          jdbcAsyncJobStore.claimNextJobs(
                              queueName, batchSize, workerId, Duration.ofSeconds(30));
                      if (claimed.isEmpty()) {
                        Thread.sleep(5);
                        continue;
                      }

                      for (AsyncJobRecord job : claimed) {
                        int claimNumber =
                            claimsById
                                .computeIfAbsent(job.id(), ignored -> new AtomicInteger())
                                .incrementAndGet();
                        assertThat(claimNumber)
                            .as(
                                "job should only be claimed for deferral and completion: %s",
                                job.id())
                            .isLessThanOrEqualTo(2);

                        if (claimNumber == 1) {
                          assertThat(job.attemptCount()).isEqualTo(1);
                          assertThat(
                                  jdbcAsyncJobStore.requeue(
                                      queueName,
                                      job.id(),
                                      workerId,
                                      job.leaseToken(),
                                      Instant.now().minusSeconds(1),
                                      "{\"stage\":\"deferred\"}",
                                      null))
                              .isTrue();
                        } else {
                          assertThat(job.attemptCount()).isEqualTo(2);
                          assertThat(job.jobData()).isEqualTo("{\"stage\":\"deferred\"}");
                          assertThat(completedIds.add(job.id()))
                              .as("job should only complete once: %s", job.id())
                              .isTrue();
                          assertThat(
                                  jdbcAsyncJobStore.markDone(
                                      queueName,
                                      job.id(),
                                      workerId,
                                      job.leaseToken(),
                                      "{\"stage\":\"done\"}"))
                              .isTrue();
                          completed++;
                        }
                      }
                    }
                    return completed;
                  } catch (Throwable throwable) {
                    stop.set(true);
                    throw throwable;
                  }
                }));
      }

      start.countDown();
      int completed = 0;
      for (Future<Integer> future : futures) {
        completed += future.get(30, TimeUnit.SECONDS);
      }

      assertThat(completed).isEqualTo(jobCount);
      assertThat(completedIds).hasSize(jobCount);
      assertThat(claimsById).hasSize(jobCount);
      assertThat(claimsById.values()).allSatisfy(claims -> assertThat(claims.get()).isEqualTo(2));
      assertThat(statusCount(queueName, AsyncJobStatus.DONE)).isEqualTo(jobCount);
      assertThat(statusCount(queueName, AsyncJobStatus.QUEUED)).isZero();
      assertThat(statusCount(queueName, AsyncJobStatus.RUNNING)).isZero();
      assertThat(statusCount(queueName, AsyncJobStatus.FAILED)).isZero();
      assertThat(jdbcAsyncJobStore.findByStatus(queueName, AsyncJobStatus.DONE, jobCount))
          .hasSize(jobCount)
          .allSatisfy(
              job -> {
                assertThat(job.attemptCount()).isEqualTo(2);
                assertThat(job.jobData()).isEqualTo("{\"stage\":\"done\"}");
                assertThat(job.lastError()).isNull();
                assertThat(job.workerId()).isNull();
                assertThat(job.leaseToken()).isNull();
                assertThat(job.leaseUntil()).isNull();
              });
    } finally {
      stop.set(true);
      executorService.shutdownNow();
      assertThat(executorService.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
    }
  }

  @Test
  public void requeuePersistsErrorAndMarkDoneClearsLeaseAndError() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);

    Instant nextAvailableAt = Instant.now().plusMillis(50);
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                nextAvailableAt,
                "{\"step\":\"requeued\"}",
                "temporary failure"))
        .isTrue();
    assertThat(
            jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(1)))
        .isEmpty();

    Thread.sleep(80);
    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(reclaimed.jobData()).isEqualTo("{\"step\":\"requeued\"}");
    assertThat(reclaimed.lastError()).isEqualTo("temporary failure");
    assertThat(reclaimed.attemptCount()).isEqualTo(2);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", reclaimed.leaseToken(), "{\"step\":\"done\"}"))
        .isTrue();

    AsyncJobRecord done = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(done.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(done.jobData()).isEqualTo("{\"step\":\"done\"}");
    assertThat(done.lastError()).isNull();
    assertThat(done.workerId()).isNull();
    assertThat(done.leaseToken()).isNull();
    assertThat(done.leaseUntil()).isNull();
  }

  @Test
  public void storesUtcCivilDatesAcrossDstAndPortableBounds() {
    for (String text :
        List.of(
            "1970-01-01T00:00:00Z",
            "2026-03-08T09:59:59.123456Z",
            "2026-03-08T10:00:00.123456Z",
            "2026-11-01T08:30:00.123456Z",
            "2026-11-01T09:30:00.123456Z",
            "9999-12-31T00:00:00Z")) {
      Instant expected = Instant.parse(text);
      AsyncJobId id = jdbcAsyncJobStore.enqueue("assetlocalize", "{}", expected);
      // Assert the stored SQL date as well as the round trip: inverse conversion bugs can cancel.
      assertThat(
              jdbcTemplate.queryForObject(
                  "SELECT available_at = TIMESTAMP '"
                      + text.substring(0, text.length() - 1).replace('T', ' ')
                      + "' FROM async_job_queue WHERE id = ?",
                  Boolean.class,
                  Long.parseLong(id.value())))
          .as("UTC SQL timestamp %s", expected)
          .isTrue();
      assertThat(jdbcAsyncJobStore.getByIds(List.of(id)).get(0).availableAt()).isEqualTo(expected);
    }
  }

  @Test
  public void missingDatabaseClockFailsBeforeEnqueue() {
    JdbcAsyncJobStore missingClockStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
            AsyncJobQueueJdbcDialect.HSQL,
            "VALUES CAST(NULL AS TIMESTAMP)");
    assertThrows(
        IllegalStateException.class, () -> missingClockStore.enqueueNow("assetlocalize", "{}"));
    assertThat(jdbcTemplate.queryForObject("SELECT COUNT(*) FROM async_job_queue", Long.class))
        .isZero();
  }

  @Test
  public void enqueueNowUsesDatabaseCurrentTimestampForAvailableAt() {
    String fixedDatabaseTimestampSql = "VALUES TIMESTAMP '2099-01-01 00:00:00'";
    JdbcAsyncJobStore futureClockStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
            AsyncJobQueueJdbcDialect.HSQL,
            fixedDatabaseTimestampSql);
    Instant fixedDatabaseNow = Instant.parse("2099-01-01T00:00:00Z");

    AsyncJobId id = futureClockStore.enqueueNow("assetlocalize", "{\"step\":\"new\"}");

    AsyncJobRecord queued = futureClockStore.getByIds(List.of(id)).get(0);
    assertThat(queued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(queued.availableAt()).isEqualTo(fixedDatabaseNow);
    assertThat(queued.createdDate()).isEqualTo(fixedDatabaseNow);
    assertThat(queued.updatedDate()).isEqualTo(fixedDatabaseNow);
  }

  @Test
  public void requeueAfterUsesDatabaseCurrentTimestampForAvailableAt() {
    String fixedDatabaseTimestampSql = "VALUES TIMESTAMP '2099-01-01 00:00:00'";
    JdbcAsyncJobStore futureClockStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
            AsyncJobQueueJdbcDialect.HSQL,
            fixedDatabaseTimestampSql);
    Instant fixedDatabaseNow = Instant.parse("2099-01-01T00:00:00Z");
    AsyncJobId id = futureClockStore.enqueue("assetlocalize", "{\"step\":\"new\"}", Instant.EPOCH);
    AsyncJobRecord claimed =
        futureClockStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(30))
            .get(0);

    assertThat(
            futureClockStore.requeueAfter(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                Duration.ofSeconds(5),
                null,
                "retry later"))
        .isTrue();

    AsyncJobRecord requeued = futureClockStore.getByIds(List.of(id)).get(0);
    assertThat(requeued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(requeued.availableAt()).isEqualTo(fixedDatabaseNow.plusSeconds(5));
    assertThat(requeued.lastError()).isEqualTo("retry later");
  }

  @Test
  public void requeueFailedNowUsesDatabaseCurrentTimestampForAvailableAt() {
    String fixedDatabaseTimestampSql = "VALUES TIMESTAMP '2099-01-01 00:00:00'";
    JdbcAsyncJobStore futureClockStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
            AsyncJobQueueJdbcDialect.HSQL,
            fixedDatabaseTimestampSql);
    Instant fixedDatabaseNow = Instant.parse("2099-01-01T00:00:00Z");
    AsyncJobId id = futureClockStore.enqueue("assetlocalize", "{\"step\":\"new\"}", Instant.EPOCH);
    AsyncJobRecord claimed =
        futureClockStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(30))
            .get(0);
    assertThat(
            futureClockStore.markFailed(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), null, "operator replay"))
        .isTrue();

    assertThat(futureClockStore.requeueFailedNow("assetlocalize", id, null)).isTrue();

    AsyncJobRecord requeued = futureClockStore.getByIds(List.of(id)).get(0);
    assertThat(requeued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(requeued.availableAt()).isEqualTo(fixedDatabaseNow);
    assertThat(requeued.attemptCount()).isZero();
    assertThat(requeued.lastError()).isEqualTo("operator replay");
  }

  @Test
  public void markFailedPersistsTerminalStateAndPreventsReclaim() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                "{\"step\":\"failed\"}",
                "boom"))
        .isTrue();

    AsyncJobRecord failed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(failed.status()).isEqualTo(AsyncJobStatus.FAILED);
    assertThat(failed.jobData()).isEqualTo("{\"step\":\"failed\"}");
    assertThat(failed.lastError()).isEqualTo("boom");
    assertThat(failed.workerId()).isNull();
    assertThat(failed.leaseToken()).isNull();
    assertThat(failed.leaseUntil()).isNull();
    assertThat(
            jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(1)))
        .isEmpty();
    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactly(new AsyncJobStatusCount(AsyncJobStatus.FAILED, 1));
  }

  @Test
  public void schemaRejectsInvalidIdStatusAttemptAndLeaseOwnerShape() {
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          id,
          queue_name,
          status,
          available_at,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          0,
          'assetlocalize',
          'queued',
          CURRENT_TIMESTAMP,
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'unknown',
          CURRENT_TIMESTAMP,
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'queued',
          CURRENT_TIMESTAMP,
          '{}',
          102,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'queued',
          CURRENT_TIMESTAMP,
          '{}',
          -1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'running',
          CURRENT_TIMESTAMP,
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          lease_until,
          worker_id,
          lease_token,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'queued',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP,
          'worker-a',
          'lease-token',
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
  }

  @Test
  public void claimSaturatesAttemptCountAtSchemaCap() {
    Instant now = Instant.now();
    jdbcTemplate.update(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          created_date,
          updated_date
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        "assetlocalize",
        AsyncJobStatus.QUEUED.getDatabaseValue(),
        Timestamp.from(now.minusSeconds(1)),
        "{}",
        AsyncJobQueueValidation.STORED_ATTEMPT_COUNT_MAX,
        Timestamp.from(now.minusSeconds(1)),
        Timestamp.from(now.minusSeconds(1)));

    List<AsyncJobRecord> claimed =
        jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(10));

    assertThat(claimed).hasSize(1);
    assertThat(claimed.get(0).attemptCount())
        .isEqualTo(AsyncJobQueueValidation.STORED_ATTEMPT_COUNT_MAX);
    assertThat(claimed.get(0).status()).isEqualTo(AsyncJobStatus.RUNNING);
  }

  @Test
  public void storeTransitionsTruncateLastErrorBeforeJdbcWrite() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    String longError = "x".repeat(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH + 1);

    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                Instant.now().minusSeconds(1),
                null,
                longError))
        .isTrue();

    AsyncJobRecord requeued = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(requeued.lastError()).hasSize(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH);

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize", id, "worker-a", reclaimed.leaseToken(), null, longError))
        .isTrue();

    AsyncJobRecord failed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(failed.lastError()).hasSize(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH);
  }

  @Test
  public void schemaRejectsOversizedLastErrorWrittenDirectly() {
    String oversizedLastError = "x".repeat(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH + 1);

    assertThrows(
        DataIntegrityViolationException.class,
        () ->
            jdbcTemplate.update(
                """
                INSERT INTO async_job_queue (
                  queue_name,
                  status,
                  available_at,
                  job_data,
                  attempt_count,
                  last_error
                ) VALUES (?, ?, ?, ?, ?, ?)
                """,
                "assetlocalize",
                AsyncJobStatus.FAILED.getDatabaseValue(),
                Timestamp.from(Instant.now()),
                "{}",
                1,
                oversizedLastError));
  }

  @Test
  public void schemaRejectsOversizedJobDataWrittenDirectly() {
    String oversizedJobData = "x".repeat(AsyncJobQueueValidation.JOB_DATA_MAX_LENGTH + 1);

    assertThrows(
        DataIntegrityViolationException.class,
        () ->
            jdbcTemplate.update(
                """
                INSERT INTO async_job_queue (
                  queue_name,
                  status,
                  available_at,
                  job_data,
                  attempt_count
                ) VALUES (?, ?, ?, ?, ?)
                """,
                "assetlocalize",
                AsyncJobStatus.QUEUED.getDatabaseValue(),
                Timestamp.from(Instant.now()),
                oversizedJobData,
                0));
  }

  @Test
  public void schemaRejectsFailedRowsWithoutPersistedErrorWrittenDirectly() {
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          last_error
        ) VALUES (
          'assetlocalize',
          'failed',
          CURRENT_TIMESTAMP,
          '{}',
          1,
          NULL
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          last_error
        ) VALUES (
          'assetlocalize',
          'failed',
          CURRENT_TIMESTAMP,
          '{}',
          1,
          '   '
        )
        """);
  }

  @Test
  public void schemaRejectsDoneRowsWithPersistedErrorWrittenDirectly() {
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          last_error
        ) VALUES (
          'assetlocalize',
          'done',
          CURRENT_TIMESTAMP,
          '{}',
          1,
          'stale failure'
        )
        """);
  }

  @Test
  public void findByStatusAndRequeueFailedSupportOperatorReplay() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), null, "boom"))
        .isTrue();

    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 10))
        .extracting(AsyncJobRecord::id)
        .containsExactly(id);
    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 0)).isEmpty();

    assertThat(
            jdbcAsyncJobStore.requeueFailed(
                "assetlocalize",
                id,
                Instant.now().minusSeconds(1),
                "{\"step\":\"operator-fixed\"}"))
        .isTrue();

    AsyncJobRecord replayed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(replayed.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(replayed.jobData()).isEqualTo("{\"step\":\"operator-fixed\"}");
    assertThat(replayed.attemptCount()).isEqualTo(0);
    assertThat(replayed.lastError()).isEqualTo("boom");
    assertThat(replayed.workerId()).isNull();
    assertThat(replayed.leaseToken()).isNull();
    assertThat(replayed.leaseUntil()).isNull();
    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 10))
        .isEmpty();

    AsyncJobRecord replayClaim =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(5))
            .get(0);
    assertThat(replayClaim.attemptCount()).isEqualTo(1);
    assertThat(replayClaim.lastError()).isEqualTo("boom");
  }

  @Test
  public void requeueFailedIgnoresNonFailedJobs() {
    AsyncJobId id = jdbcAsyncJobStore.enqueue("assetlocalize", "{}", Instant.now().minusSeconds(1));

    assertThat(jdbcAsyncJobStore.requeueFailed("assetlocalize", id, Instant.now(), "{\"v\":2}"))
        .isFalse();

    AsyncJobRecord queued = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(queued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(queued.jobData()).isEqualTo("{}");
  }

  @Test(timeout = 5_000)
  public void inspectionReplayReturnsCommittedRowWhenSuccessTelemetryFails() {
    assertInspectionReplaySurvivesTelemetryFailure(false);
  }

  @Test(timeout = 5_000)
  public void inspectionReplayStillNotifiesWhenLocalWakeupAndItsFailureTelemetryFail() {
    assertInspectionReplaySurvivesTelemetryFailure(true);
  }

  private void assertInspectionReplaySurvivesTelemetryFailure(boolean localWakeupFails) {
    String queueName = "assetlocalize";
    String replacement = "{\"step\":\"operator-fixed\"}";
    String retainedError = "original terminal failure";
    DataSource dataSource = jdbcTemplate.getDataSource();
    AtomicInteger updates = new AtomicInteger();
    NamedParameterJdbcTemplate observingJdbc =
        new NamedParameterJdbcTemplate(dataSource) {
          @Override
          public int update(String sql, SqlParameterSource params) {
            assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isTrue();
            updates.incrementAndGet();
            return super.update(sql, params);
          }
        };
    JdbcAsyncJobStore store =
        new JdbcAsyncJobStore(
            observingJdbc,
            AsyncJobQueueJdbcDialect.HSQL,
            new DataSourceTransactionManager(dataSource));
    AsyncJobId id = store.enqueueNow(queueName, "{\"step\":\"original\"}");
    AsyncJobRecord originalClaim =
        store.claimNextJobs(queueName, 1, "worker-a", Duration.ofMinutes(1)).get(0);
    assertThat(originalClaim.attemptCount()).isEqualTo(1);
    assertThat(
            store.markFailed(
                queueName, id, "worker-a", originalClaim.leaseToken(), null, retainedError))
        .isTrue();
    AsyncJobRecord failed = store.getByIds(List.of(id)).get(0);
    assertThat(failed.status()).isEqualTo(AsyncJobStatus.FAILED);
    updates.set(0);

    AsyncJobQueueCoordinator coordinator = mock(AsyncJobQueueCoordinator.class);
    AsyncJobQueueWakeupNotifier notifier = mock(AsyncJobQueueWakeupNotifier.class);
    AtomicBoolean wakeupInTransaction = new AtomicBoolean();
    AtomicReference<AsyncJobRecord> committedAtWakeup = new AtomicReference<>();
    doAnswer(
            invocation -> {
              wakeupInTransaction.set(
                  TransactionSynchronizationManager.isActualTransactionActive());
              // This independent read proves replay committed before wakeups and telemetry.
              committedAtWakeup.set(jdbcAsyncJobStore.getByIds(List.of(id)).get(0));
              if (localWakeupFails) {
                throw new IllegalStateException("local wakeup unavailable");
              }
              return null;
            })
        .when(coordinator)
        .triggerPollNow(queueName);
    SimpleMeterRegistry registry = new SimpleMeterRegistry();
    try {
      registry.gauge(
          "asyncJobQueue.inspection.requeue",
          Tags.of("queueName", queueName, "result", "succeeded"),
          1);
      if (localWakeupFails) {
        registry.gauge(
            "asyncJobQueue.inspection.requeueWakeup.failed", Tags.of("queueName", queueName), 1);
      }
      AsyncJobQueueInspectionService.AsyncJobDetails result =
          new AsyncJobQueueInspectionService(store, coordinator, notifier, registry)
              .requeueFailedJob(queueName, id.value(), replacement);

      assertThat(result.id()).isEqualTo(id.value());
      assertThat(result.queueName()).isEqualTo(queueName);
      assertThat(result.status()).isEqualTo("queued");
      assertThat(result.jobData()).isEqualTo(replacement);
      assertThat(result.attemptCount()).isZero();
      assertThat(result.lastError()).isEqualTo(retainedError);
      assertThat(result.workerId()).isNull();
      assertThat(result.leaseUntil()).isNull();
      AsyncJobRecord replayed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
      assertThat(replayed.status()).isEqualTo(AsyncJobStatus.QUEUED);
      assertThat(replayed.jobData()).isEqualTo(replacement);
      assertThat(replayed.attemptCount()).isZero();
      assertThat(replayed.lastError()).isEqualTo(retainedError);
      assertThat(replayed.createdDate()).isEqualTo(failed.createdDate());
      assertThat(replayed.availableAt()).isEqualTo(result.availableAt());
      assertThat(replayed.updatedDate()).isEqualTo(result.updatedDate());
      assertThat(replayed.workerId()).isNull();
      assertThat(replayed.leaseToken()).isNull();
      assertThat(replayed.leaseUntil()).isNull();
      assertThat(wakeupInTransaction.get()).isFalse();
      assertThat(committedAtWakeup.get()).isEqualTo(replayed);
      assertThat(updates.get()).isEqualTo(1);
      var wakeupOrder = inOrder(coordinator, notifier);
      wakeupOrder.verify(coordinator).triggerPollNow(queueName);
      wakeupOrder.verify(notifier).notifyJobAvailable(queueName, id);
      verifyNoMoreInteractions(coordinator, notifier);
      assertThat(TransactionSynchronizationManager.isActualTransactionActive()).isFalse();
      assertThat(TransactionSynchronizationManager.hasResource(dataSource)).isFalse();

      List<AsyncJobRecord> replayClaims =
          store.claimNextJobs(queueName, 2, "worker-b", Duration.ofMinutes(1));
      assertThat(replayClaims).hasSize(1);
      AsyncJobRecord replayClaim = replayClaims.get(0);
      assertThat(replayClaim.id()).isEqualTo(id);
      assertThat(replayClaim.status()).isEqualTo(AsyncJobStatus.RUNNING);
      assertThat(replayClaim.attemptCount()).isEqualTo(1);
      assertThat(replayClaim.jobData()).isEqualTo(replacement);
      assertThat(replayClaim.lastError()).isEqualTo(retainedError);
      assertThat(replayClaim.leaseToken()).isNotEqualTo(originalClaim.leaseToken());
      assertThat(store.claimNextJobs(queueName, 1, "worker-c", Duration.ofMinutes(1))).isEmpty();
    } finally {
      registry.close();
    }
  }

  @Test
  public void readyStatusCountsOnlyClaimableQueuedJobs() {
    Instant oldReadyAt = Instant.now().minusSeconds(30);
    jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"old-ready\"}", oldReadyAt);
    jdbcAsyncJobStore.enqueue(
        "assetlocalize", "{\"name\":\"new-ready\"}", Instant.now().minusSeconds(1));
    jdbcAsyncJobStore.enqueue(
        "assetlocalize", "{\"name\":\"delayed\"}", Instant.now().plusSeconds(60));
    AsyncJobRecord running =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(running.jobData()).isEqualTo("{\"name\":\"old-ready\"}");

    AsyncJobReadyStatus readyStatus = jdbcAsyncJobStore.readyStatus("assetlocalize");

    assertThat(readyStatus.count()).isEqualTo(1);
    assertThat(readyStatus.oldestAvailableAt()).isBeforeOrEqualTo(readyStatus.observedAt());
    assertThat(readyStatus.oldestAvailableAt()).isAfter(oldReadyAt);
  }

  @Test
  public void expiredLeaseStatusCountsOnlyRunningJobsWithExpiredLeases() throws Exception {
    jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"expired\"}", Instant.now());
    jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofMillis(50)).get(0);

    assertThat(jdbcAsyncJobStore.expiredLeaseStatus("assetlocalize").count()).isEqualTo(0);

    Thread.sleep(80);

    AsyncJobExpiredLeaseStatus expiredLeaseStatus =
        jdbcAsyncJobStore.expiredLeaseStatus("assetlocalize");

    assertThat(expiredLeaseStatus.count()).isEqualTo(1);
    assertThat(expiredLeaseStatus.oldestLeaseUntil())
        .isBeforeOrEqualTo(expiredLeaseStatus.observedAt());
  }

  @Test
  public void deleteTerminalJobsDeletesOnlyBoundedMatchingTerminalRows() {
    completeJob("assetlocalize", "{\"name\":\"done-1\"}");
    completeJob("assetlocalize", "{\"name\":\"done-2\"}");
    failJob("assetlocalize", "{\"name\":\"failed\"}");
    jdbcAsyncJobStore.enqueue(
        "assetlocalize", "{\"name\":\"queued\"}", Instant.now().plusSeconds(30));
    completeJob("stats", "{\"name\":\"other-queue\"}");

    Instant cutoffAfterCreatedRows = Instant.now().plusSeconds(1);

    assertThat(
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.DONE, cutoffAfterCreatedRows, 1))
        .isEqualTo(1);

    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactlyInAnyOrder(
            new AsyncJobStatusCount(AsyncJobStatus.DONE, 1),
            new AsyncJobStatusCount(AsyncJobStatus.FAILED, 1),
            new AsyncJobStatusCount(AsyncJobStatus.QUEUED, 1));
    assertThat(jdbcAsyncJobStore.countByStatus("stats"))
        .containsExactly(new AsyncJobStatusCount(AsyncJobStatus.DONE, 1));

    assertThat(
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.FAILED, cutoffAfterCreatedRows, 10))
        .isEqualTo(1);
    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 10))
        .isEmpty();
  }

  @Test
  public void deleteTerminalJobsRejectsNonTerminalStatusAndHonorsLimit() {
    completeJob("assetlocalize", "{\"name\":\"done\"}");

    assertThat(
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.DONE, Instant.now().plusSeconds(1), 0))
        .isZero();
    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.QUEUED, Instant.now().plusSeconds(1), 10));

    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.DONE, 10)).hasSize(1);
  }

  @Test
  public void storeMethodsRejectExcessiveLimits() {
    int excessiveLimit = AsyncJobQueueValidation.STORE_QUERY_LIMIT_MAX + 1;
    completeJob("assetlocalize", "{\"name\":\"done\"}");

    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.claimNextJobs(
                "assetlocalize", excessiveLimit, "worker-a", Duration.ofSeconds(5)));
    assertThrows(
        IllegalArgumentException.class,
        () -> jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.DONE, excessiveLimit));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize",
                AsyncJobStatus.DONE,
                Instant.now().plusSeconds(1),
                excessiveLimit));
    assertThrows(IllegalArgumentException.class, () -> jdbcAsyncJobStore.getByIds(manyIds()));
  }

  @Test
  public void invalidNumericIdsFailFast() {
    assertThrows(
        IllegalArgumentException.class,
        () -> jdbcAsyncJobStore.getByIds(List.of(new AsyncJobId("abc"))));
  }

  @Test
  public void rejectsAvailableAtOutsideDatabaseTimestampBoundsBeforeJdbcWrite() {
    IllegalArgumentException tooEarly =
        assertThrows(
            IllegalArgumentException.class,
            () ->
                jdbcAsyncJobStore.enqueue(
                    "assetlocalize",
                    "{}",
                    AsyncJobQueueValidation.DATABASE_TIMESTAMP_MIN.minusNanos(1)));
    IllegalArgumentException tooLate =
        assertThrows(
            IllegalArgumentException.class,
            () ->
                jdbcAsyncJobStore.enqueue(
                    "assetlocalize",
                    "{}",
                    AsyncJobQueueValidation.DATABASE_TIMESTAMP_MAX.plusNanos(1)));

    assertThat(tooEarly).hasMessageContaining("availableAt must be between");
    assertThat(tooLate).hasMessageContaining("availableAt must be between");
  }

  @Test
  public void requeueMethodsValidateInputsBeforeReadingDatabaseClock() {
    JdbcAsyncJobStore brokenClockStore = storeWithBrokenDatabaseClock();
    AsyncJobId id = new AsyncJobId("1");
    Instant outsideDatabaseTimestampRange =
        AsyncJobQueueValidation.DATABASE_TIMESTAMP_MAX.plusNanos(1);

    assertThrows(
        IllegalArgumentException.class,
        () ->
            brokenClockStore.requeue(
                " ", id, "worker-a", "lease-token", Instant.now(), null, null));
    assertThrows(
        NullPointerException.class,
        () ->
            brokenClockStore.requeue(
                "assetlocalize", null, "worker-a", "lease-token", Instant.now(), null, null));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            brokenClockStore.requeue(
                "assetlocalize", id, " ", "lease-token", Instant.now(), null, null));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            brokenClockStore.requeue(
                "assetlocalize", id, "worker-a", " ", Instant.now(), null, null));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            brokenClockStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                "lease-token",
                outsideDatabaseTimestampRange,
                null,
                null));
    assertThrows(
        NullPointerException.class,
        () ->
            brokenClockStore.requeueAfter(
                "assetlocalize", id, "worker-a", "lease-token", null, null, null));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            brokenClockStore.requeueFailed(
                "assetlocalize", id, outsideDatabaseTimestampRange, null));
    assertThrows(
        NullPointerException.class,
        () -> brokenClockStore.requeueFailedNow("assetlocalize", null, null));
  }

  @Test
  public void rejectsLeaseDurationOutsideDatabaseTimestampBoundsBeforeClaimWrite() {
    jdbcAsyncJobStore.enqueue("assetlocalize", "{}", Instant.now().minusSeconds(1));

    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () ->
                jdbcAsyncJobStore.claimNextJobs(
                    "assetlocalize", 1, "worker-a", Duration.ofSeconds(Long.MAX_VALUE)));

    assertThat(exception).hasMessageContaining("leaseUntil");
  }

  @Test
  public void rejectsQueueNamesOutsideSchemaBounds() {
    assertThrows(
        IllegalArgumentException.class, () -> jdbcAsyncJobStore.enqueue(" ", "{}", Instant.now()));

    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.enqueue(
                "x".repeat(AsyncJobQueueValidation.QUEUE_NAME_MAX_LENGTH + 1),
                "{}",
                Instant.now()));
  }

  @Test
  public void rejectsWorkerIdsOutsideSchemaBounds() {
    jdbcAsyncJobStore.enqueue("assetlocalize", "{}", Instant.now().minusSeconds(1));

    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.claimNextJobs(
                "assetlocalize",
                1,
                "x".repeat(AsyncJobQueueValidation.WORKER_ID_MAX_LENGTH + 1),
                Duration.ofSeconds(1)));
  }

  private AsyncJobId completeJob(String queueName, String jobData) {
    AsyncJobId id = jdbcAsyncJobStore.enqueue(queueName, jobData, Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore.claimNextJobs(queueName, 1, "worker-a", Duration.ofSeconds(5)).get(0);
    assertThat(jdbcAsyncJobStore.markDone(queueName, id, "worker-a", claimed.leaseToken(), null))
        .isTrue();
    return id;
  }

  private AsyncJobId failJob(String queueName, String jobData) {
    AsyncJobId id = jdbcAsyncJobStore.enqueue(queueName, jobData, Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore.claimNextJobs(queueName, 1, "worker-a", Duration.ofSeconds(5)).get(0);
    assertThat(
            jdbcAsyncJobStore.markFailed(
                queueName, id, "worker-a", claimed.leaseToken(), null, "boom"))
        .isTrue();
    return id;
  }

  private List<AsyncJobId> manyIds() {
    return java.util.stream.IntStream.rangeClosed(0, AsyncJobQueueValidation.STORE_QUERY_LIMIT_MAX)
        .mapToObj(index -> new AsyncJobId(String.valueOf(index + 1)))
        .toList();
  }

  private JdbcAsyncJobStore storeWithBrokenDatabaseClock() {
    return new JdbcAsyncJobStore(
        new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
        AsyncJobQueueJdbcDialect.HSQL,
        "SELECT missing_clock FROM missing_clock_table");
  }

  private void assertSchemaViolation(String sql) {
    assertThrows(DataIntegrityViolationException.class, () -> jdbcTemplate.execute(sql));
  }

  private long statusCount(String queueName, AsyncJobStatus status) {
    return jdbcAsyncJobStore.countByStatus(queueName).stream()
        .filter(statusCount -> statusCount.status() == status)
        .mapToLong(AsyncJobStatusCount::count)
        .findFirst()
        .orElse(0);
  }

  private static class ClaimRaceNamedParameterJdbcTemplate extends NamedParameterJdbcTemplate {

    private final JdbcTemplate jdbcTemplate;
    private final AsyncJobId id;
    private final String raceSql;
    private final AtomicBoolean raceInjected = new AtomicBoolean();

    ClaimRaceNamedParameterJdbcTemplate(DataSource dataSource, AsyncJobId id, String raceSql) {
      super(dataSource);
      this.jdbcTemplate = new JdbcTemplate(dataSource);
      this.id = id;
      this.raceSql = raceSql;
    }

    @Override
    public <T> List<T> query(String sql, SqlParameterSource paramSource, RowMapper<T> rowMapper) {
      List<T> rows = super.query(sql, paramSource, rowMapper);
      if (!rows.isEmpty()
          && sql.equals(AsyncJobQueueJdbcDialect.HSQL.claimNextJobsSql())
          && raceInjected.compareAndSet(false, true)) {
        jdbcTemplate.update(raceSql, Long.parseLong(id.value()));
      }
      return rows;
    }
  }

  private static class ClaimReadbackDroppingNamedParameterJdbcTemplate
      extends NamedParameterJdbcTemplate {

    ClaimReadbackDroppingNamedParameterJdbcTemplate(DataSource dataSource) {
      super(dataSource);
    }

    @Override
    public <T> List<T> query(String sql, SqlParameterSource paramSource, RowMapper<T> rowMapper) {
      if (sql.contains("WHERE id IN (:ids)")) {
        return List.of();
      }
      return super.query(sql, paramSource, rowMapper);
    }
  }
}
