package com.box.l10n.mojito.queue;

import static org.assertj.core.api.Assertions.assertThat;
import static org.junit.Assert.assertThrows;

import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.Future;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import javax.sql.DataSource;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.dao.DataIntegrityViolationException;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.core.RowMapper;
import org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate;
import org.springframework.jdbc.core.namedparam.SqlParameterSource;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

public class JdbcAsyncJobStoreTest {

  private JdbcTemplate jdbcTemplate;
  private JdbcAsyncJobStore jdbcAsyncJobStore;

  @Before
  public void setup() {
    DriverManagerDataSource dataSource = new DriverManagerDataSource();
    dataSource.setDriverClassName("org.hsqldb.jdbc.JDBCDriver");
    dataSource.setUrl(
        "jdbc:hsqldb:mem:async_job_queue_" + UUID.randomUUID() + ";DB_CLOSE_DELAY=-1");
    dataSource.setUsername("sa");
    dataSource.setPassword("");

    jdbcTemplate = new JdbcTemplate(dataSource);
    jdbcTemplate.execute(
        """
        CREATE TABLE async_job_queue (
          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
          queue_name VARCHAR(64) NOT NULL,
          status VARCHAR(16) NOT NULL,
          available_at TIMESTAMP(6) NOT NULL,
          lease_until TIMESTAMP(6) NULL,
          worker_id VARCHAR(128) NULL,
          lease_token VARCHAR(64) NULL,
          job_data LONGVARCHAR NOT NULL,
          attempt_count INTEGER DEFAULT 0 NOT NULL,
          last_error LONGVARCHAR NULL,
          created_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
          updated_date TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
          CONSTRAINT C_ASYNC_JOB_QUEUE_STATUS
            CHECK (status IN ('queued', 'running', 'done', 'failed')),
          CONSTRAINT C_ASYNC_JOB_QUEUE_ATTEMPT_NONNEGATIVE
            CHECK (attempt_count >= 0),
          CONSTRAINT C_ASYNC_JOB_QUEUE_RUNNING_LEASE_OWNER
            CHECK (
              (status = 'running' AND lease_until IS NOT NULL AND worker_id IS NOT NULL AND lease_token IS NOT NULL)
              OR (status <> 'running' AND lease_until IS NULL AND worker_id IS NULL AND lease_token IS NULL)
            )
        )
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_AVAILABLE_ID
          ON async_job_queue (queue_name, status, available_at, id)
        """);
    jdbcTemplate.execute(
        """
        CREATE INDEX I_ASYNC_JOB_QUEUE_QNAME_STATUS_LEASE_ID
          ON async_job_queue (queue_name, status, lease_until, id)
        """);
    jdbcAsyncJobStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(dataSource), AsyncJobQueueJdbcDialect.HSQL);
  }

  @After
  public void tearDown() {
    jdbcTemplate.execute("DROP TABLE async_job_queue IF EXISTS");
  }

  @Test
  public void enqueueAndClaimFiltersByQueueAvailabilityAndOrder() {
    Instant now = Instant.now();
    AsyncJobId firstReadyId =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"first\"}", now.minusSeconds(2));
    jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"later\"}", now.plusSeconds(30));
    jdbcAsyncJobStore.enqueue("stats", "{\"name\":\"other-queue\"}", now.minusSeconds(3));
    AsyncJobId secondReadyId =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"name\":\"second\"}", now.minusSeconds(1));

    List<AsyncJobRecord> claimed =
        jdbcAsyncJobStore.claimNextJobs("assetlocalize", 10, "worker-a", Duration.ofSeconds(10));

    assertThat(claimed).hasSize(2);
    assertThat(claimed.get(0).id()).isEqualTo(firstReadyId);
    assertThat(claimed.get(1).id()).isEqualTo(secondReadyId);
    assertThat(claimed).allMatch(job -> job.status() == AsyncJobStatus.RUNNING);
    assertThat(claimed).allMatch(job -> "worker-a".equals(job.workerId()));
    assertThat(claimed).allMatch(job -> job.attemptCount() == 1);
    assertThat(claimed).allMatch(job -> job.leaseToken() != null && !job.leaseToken().isBlank());
    assertThat(claimed).allMatch(job -> job.leaseUntil().isAfter(job.updatedDate()));
    assertThat(claimed).allMatch(job -> !job.leaseReclaimed());

    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactlyInAnyOrder(
            new AsyncJobStatusCount(AsyncJobStatus.RUNNING, 2),
            new AsyncJobStatusCount(AsyncJobStatus.QUEUED, 1));
  }

  @Test
  public void leaseFencingRejectsWrongOwnerTokenAndExpiredOwner() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofMillis(50))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.heartbeat(
                "assetlocalize", id, "worker-a", "wrong-token", Duration.ofSeconds(1)))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-b", claimed.leaseToken(), "{\"v\":2}"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-b",
                claimed.leaseToken(),
                Instant.now(),
                "{\"v\":2}",
                "wrong owner"))
        .isFalse();

    Thread.sleep(80);
    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), "{\"v\":2}"))
        .isFalse();

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(1))
            .get(0);
    assertThat(reclaimed.id()).isEqualTo(id);
    assertThat(reclaimed.workerId()).isEqualTo("worker-b");
    assertThat(reclaimed.leaseToken()).isNotEqualTo(claimed.leaseToken());
    assertThat(reclaimed.attemptCount()).isEqualTo(2);
    assertThat(reclaimed.leaseReclaimed()).isTrue();
  }

  @Test
  public void reclaimedLeaseFencesStaleOwnerTransitions() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    AsyncJobRecord firstClaim =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofMillis(50))
            .get(0);

    Thread.sleep(80);

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(5))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", firstClaim.leaseToken(), "{\"v\":\"stale\"}"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                firstClaim.leaseToken(),
                Instant.now().plusSeconds(1),
                "{\"v\":\"stale\"}",
                "stale requeue"))
        .isFalse();
    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize", id, "worker-a", firstClaim.leaseToken(), null, "stale failure"))
        .isFalse();

    AsyncJobRecord running = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(running.status()).isEqualTo(AsyncJobStatus.RUNNING);
    assertThat(running.workerId()).isEqualTo("worker-b");
    assertThat(running.leaseToken()).isEqualTo(reclaimed.leaseToken());
    assertThat(running.attemptCount()).isEqualTo(2);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-b", reclaimed.leaseToken(), "{\"v\":\"done\"}"))
        .isTrue();
    AsyncJobRecord done = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(done.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(done.jobData()).isEqualTo("{\"v\":\"done\"}");
    assertThat(done.lastError()).isNull();
  }

  @Test
  public void claimUpdateRechecksClaimableStateAfterCandidateSelection() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    JdbcAsyncJobStore racingStore =
        new JdbcAsyncJobStore(
            new ClaimRaceNamedParameterJdbcTemplate(
                jdbcTemplate.getDataSource(),
                id,
                """
                UPDATE async_job_queue
                SET status = 'done', updated_date = CURRENT_TIMESTAMP
                WHERE id = ?
                """),
            AsyncJobQueueJdbcDialect.HSQL);

    List<AsyncJobRecord> claimed =
        racingStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5));

    assertThat(claimed).isEmpty();
    AsyncJobRecord changedJob = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(changedJob.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(changedJob.attemptCount()).isZero();
    assertThat(changedJob.workerId()).isNull();
    assertThat(changedJob.leaseToken()).isNull();
    assertThat(changedJob.leaseUntil()).isNull();
  }

  @Test
  public void claimUpdateRequiresSelectedStateAfterCandidateSelection() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue("assetlocalize", "{\"v\":1}", Instant.now().minusSeconds(1));
    JdbcAsyncJobStore racingStore =
        new JdbcAsyncJobStore(
            new ClaimRaceNamedParameterJdbcTemplate(
                jdbcTemplate.getDataSource(),
                id,
                """
                UPDATE async_job_queue
                SET
                  status = 'running',
                  lease_until = TIMESTAMP '2000-01-01 00:00:00',
                  worker_id = 'other-worker',
                  lease_token = 'other-token',
                  updated_date = CURRENT_TIMESTAMP
                WHERE id = ?
                """),
            AsyncJobQueueJdbcDialect.HSQL);

    List<AsyncJobRecord> claimed =
        racingStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5));

    assertThat(claimed).isEmpty();
    AsyncJobRecord changedJob = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(changedJob.status()).isEqualTo(AsyncJobStatus.RUNNING);
    assertThat(changedJob.attemptCount()).isZero();
    assertThat(changedJob.workerId()).isEqualTo("other-worker");
    assertThat(changedJob.leaseToken()).isEqualTo("other-token");
    assertThat(changedJob.leaseUntil()).isBefore(Instant.now());
  }

  @Test
  public void concurrentClaimsCompleteEachJobOnce() throws Exception {
    String queueName = "assetlocalize";
    int jobCount = 80;
    int workerCount = 6;
    int batchSize = 3;
    for (int i = 0; i < jobCount; i++) {
      jdbcAsyncJobStore.enqueue(queueName, "{\"id\":" + i + "}", Instant.now().minusSeconds(1));
    }

    Set<AsyncJobId> claimedIds = ConcurrentHashMap.newKeySet();
    AtomicBoolean stop = new AtomicBoolean();
    CountDownLatch start = new CountDownLatch(1);
    ExecutorService executorService = Executors.newFixedThreadPool(workerCount);
    List<Future<Integer>> futures = new ArrayList<>();
    try {
      for (int workerIndex = 0; workerIndex < workerCount; workerIndex++) {
        String workerId = "worker-" + workerIndex;
        futures.add(
            executorService.submit(
                () -> {
                  start.await();
                  int processed = 0;
                  try {
                    while (!stop.get() && statusCount(queueName, AsyncJobStatus.DONE) < jobCount) {
                      List<AsyncJobRecord> claimed =
                          jdbcAsyncJobStore.claimNextJobs(
                              queueName, batchSize, workerId, Duration.ofSeconds(30));
                      if (claimed.isEmpty()) {
                        Thread.sleep(5);
                        continue;
                      }

                      for (AsyncJobRecord job : claimed) {
                        assertThat(claimedIds.add(job.id()))
                            .as("job should only be claimed once: %s", job.id())
                            .isTrue();
                        assertThat(
                                jdbcAsyncJobStore.markDone(
                                    queueName,
                                    job.id(),
                                    workerId,
                                    job.leaseToken(),
                                    "{\"done\":" + job.id().value() + "}"))
                            .isTrue();
                        processed++;
                      }
                    }
                    return processed;
                  } catch (Throwable throwable) {
                    stop.set(true);
                    throw throwable;
                  }
                }));
      }

      start.countDown();
      int processed = 0;
      for (Future<Integer> future : futures) {
        processed += future.get(30, TimeUnit.SECONDS);
      }

      assertThat(processed).isEqualTo(jobCount);
      assertThat(claimedIds).hasSize(jobCount);
      assertThat(statusCount(queueName, AsyncJobStatus.DONE)).isEqualTo(jobCount);
      assertThat(statusCount(queueName, AsyncJobStatus.QUEUED)).isZero();
      assertThat(statusCount(queueName, AsyncJobStatus.RUNNING)).isZero();
      assertThat(statusCount(queueName, AsyncJobStatus.FAILED)).isZero();
    } finally {
      stop.set(true);
      executorService.shutdownNow();
      assertThat(executorService.awaitTermination(10, TimeUnit.SECONDS)).isTrue();
    }
  }

  @Test
  public void requeuePersistsErrorAndMarkDoneClearsLeaseAndError() throws Exception {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);

    Instant nextAvailableAt = Instant.now().plusMillis(50);
    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                nextAvailableAt,
                "{\"step\":\"requeued\"}",
                "temporary failure"))
        .isTrue();
    assertThat(
            jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(1)))
        .isEmpty();

    Thread.sleep(80);
    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(reclaimed.jobData()).isEqualTo("{\"step\":\"requeued\"}");
    assertThat(reclaimed.lastError()).isEqualTo("temporary failure");
    assertThat(reclaimed.attemptCount()).isEqualTo(2);

    assertThat(
            jdbcAsyncJobStore.markDone(
                "assetlocalize", id, "worker-a", reclaimed.leaseToken(), "{\"step\":\"done\"}"))
        .isTrue();

    AsyncJobRecord done = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(done.status()).isEqualTo(AsyncJobStatus.DONE);
    assertThat(done.jobData()).isEqualTo("{\"step\":\"done\"}");
    assertThat(done.lastError()).isNull();
    assertThat(done.workerId()).isNull();
    assertThat(done.leaseToken()).isNull();
    assertThat(done.leaseUntil()).isNull();
  }

  @Test
  public void requeueAfterUsesDatabaseCurrentTimestampForAvailableAt() {
    String fixedDatabaseTimestampSql = "VALUES TIMESTAMP '2099-01-01 00:00:00'";
    JdbcAsyncJobStore futureClockStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
            AsyncJobQueueJdbcDialect.HSQL.claimNextJobsSql(),
            fixedDatabaseTimestampSql);
    Instant fixedDatabaseNow =
        jdbcTemplate.queryForObject(fixedDatabaseTimestampSql, Timestamp.class).toInstant();
    AsyncJobId id = futureClockStore.enqueue("assetlocalize", "{\"step\":\"new\"}", Instant.EPOCH);
    AsyncJobRecord claimed =
        futureClockStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(30))
            .get(0);

    assertThat(
            futureClockStore.requeueAfter(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                Duration.ofSeconds(5),
                null,
                "retry later"))
        .isTrue();

    AsyncJobRecord requeued = futureClockStore.getByIds(List.of(id)).get(0);
    assertThat(requeued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(requeued.availableAt()).isEqualTo(fixedDatabaseNow.plusSeconds(5));
    assertThat(requeued.lastError()).isEqualTo("retry later");
  }

  @Test
  public void requeueFailedNowUsesDatabaseCurrentTimestampForAvailableAt() {
    String fixedDatabaseTimestampSql = "VALUES TIMESTAMP '2099-01-01 00:00:00'";
    JdbcAsyncJobStore futureClockStore =
        new JdbcAsyncJobStore(
            new NamedParameterJdbcTemplate(jdbcTemplate.getDataSource()),
            AsyncJobQueueJdbcDialect.HSQL.claimNextJobsSql(),
            fixedDatabaseTimestampSql);
    Instant fixedDatabaseNow =
        jdbcTemplate.queryForObject(fixedDatabaseTimestampSql, Timestamp.class).toInstant();
    AsyncJobId id = futureClockStore.enqueue("assetlocalize", "{\"step\":\"new\"}", Instant.EPOCH);
    AsyncJobRecord claimed =
        futureClockStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(30))
            .get(0);
    assertThat(
            futureClockStore.markFailed(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), null, "operator replay"))
        .isTrue();

    assertThat(futureClockStore.requeueFailedNow("assetlocalize", id, null)).isTrue();

    AsyncJobRecord requeued = futureClockStore.getByIds(List.of(id)).get(0);
    assertThat(requeued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(requeued.availableAt()).isEqualTo(fixedDatabaseNow);
    assertThat(requeued.attemptCount()).isZero();
    assertThat(requeued.lastError()).isEqualTo("operator replay");
  }

  @Test
  public void markFailedPersistsTerminalStateAndPreventsReclaim() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);

    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                "{\"step\":\"failed\"}",
                "boom"))
        .isTrue();

    AsyncJobRecord failed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(failed.status()).isEqualTo(AsyncJobStatus.FAILED);
    assertThat(failed.jobData()).isEqualTo("{\"step\":\"failed\"}");
    assertThat(failed.lastError()).isEqualTo("boom");
    assertThat(failed.workerId()).isNull();
    assertThat(failed.leaseToken()).isNull();
    assertThat(failed.leaseUntil()).isNull();
    assertThat(
            jdbcAsyncJobStore.claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(1)))
        .isEmpty();
    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactly(new AsyncJobStatusCount(AsyncJobStatus.FAILED, 1));
  }

  @Test
  public void schemaRejectsInvalidStatusAttemptAndLeaseOwnerShape() {
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'unknown',
          CURRENT_TIMESTAMP,
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          attempt_count,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'queued',
          CURRENT_TIMESTAMP,
          '{}',
          -1,
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'running',
          CURRENT_TIMESTAMP,
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
    assertSchemaViolation(
        """
        INSERT INTO async_job_queue (
          queue_name,
          status,
          available_at,
          lease_until,
          worker_id,
          lease_token,
          job_data,
          created_date,
          updated_date
        ) VALUES (
          'assetlocalize',
          'queued',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP,
          'worker-a',
          'lease-token',
          '{}',
          CURRENT_TIMESTAMP,
          CURRENT_TIMESTAMP
        )
        """);
  }

  @Test
  public void storeTransitionsTruncateLastErrorBeforeJdbcWrite() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    String longError = "x".repeat(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH + 1);

    assertThat(
            jdbcAsyncJobStore.requeue(
                "assetlocalize",
                id,
                "worker-a",
                claimed.leaseToken(),
                Instant.now().minusSeconds(1),
                null,
                longError))
        .isTrue();

    AsyncJobRecord requeued = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(requeued.lastError()).hasSize(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH);

    AsyncJobRecord reclaimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize", id, "worker-a", reclaimed.leaseToken(), null, longError))
        .isTrue();

    AsyncJobRecord failed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(failed.lastError()).hasSize(AsyncJobQueueValidation.LAST_ERROR_MAX_LENGTH);
  }

  @Test
  public void findByStatusAndRequeueFailedSupportOperatorReplay() {
    AsyncJobId id =
        jdbcAsyncJobStore.enqueue(
            "assetlocalize", "{\"step\":\"new\"}", Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-a", Duration.ofSeconds(5))
            .get(0);
    assertThat(
            jdbcAsyncJobStore.markFailed(
                "assetlocalize", id, "worker-a", claimed.leaseToken(), null, "boom"))
        .isTrue();

    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 10))
        .extracting(AsyncJobRecord::id)
        .containsExactly(id);
    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 0)).isEmpty();

    assertThat(
            jdbcAsyncJobStore.requeueFailed(
                "assetlocalize",
                id,
                Instant.now().minusSeconds(1),
                "{\"step\":\"operator-fixed\"}"))
        .isTrue();

    AsyncJobRecord replayed = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(replayed.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(replayed.jobData()).isEqualTo("{\"step\":\"operator-fixed\"}");
    assertThat(replayed.attemptCount()).isEqualTo(0);
    assertThat(replayed.lastError()).isEqualTo("boom");
    assertThat(replayed.workerId()).isNull();
    assertThat(replayed.leaseToken()).isNull();
    assertThat(replayed.leaseUntil()).isNull();
    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 10))
        .isEmpty();

    AsyncJobRecord replayClaim =
        jdbcAsyncJobStore
            .claimNextJobs("assetlocalize", 1, "worker-b", Duration.ofSeconds(5))
            .get(0);
    assertThat(replayClaim.attemptCount()).isEqualTo(1);
    assertThat(replayClaim.lastError()).isEqualTo("boom");
  }

  @Test
  public void requeueFailedIgnoresNonFailedJobs() {
    AsyncJobId id = jdbcAsyncJobStore.enqueue("assetlocalize", "{}", Instant.now().minusSeconds(1));

    assertThat(jdbcAsyncJobStore.requeueFailed("assetlocalize", id, Instant.now(), "{\"v\":2}"))
        .isFalse();

    AsyncJobRecord queued = jdbcAsyncJobStore.getByIds(List.of(id)).get(0);
    assertThat(queued.status()).isEqualTo(AsyncJobStatus.QUEUED);
    assertThat(queued.jobData()).isEqualTo("{}");
  }

  @Test
  public void deleteTerminalJobsDeletesOnlyBoundedMatchingTerminalRows() {
    completeJob("assetlocalize", "{\"name\":\"done-1\"}");
    completeJob("assetlocalize", "{\"name\":\"done-2\"}");
    failJob("assetlocalize", "{\"name\":\"failed\"}");
    jdbcAsyncJobStore.enqueue(
        "assetlocalize", "{\"name\":\"queued\"}", Instant.now().plusSeconds(30));
    completeJob("stats", "{\"name\":\"other-queue\"}");

    Instant cutoffAfterCreatedRows = Instant.now().plusSeconds(1);

    assertThat(
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.DONE, cutoffAfterCreatedRows, 1))
        .isEqualTo(1);

    assertThat(jdbcAsyncJobStore.countByStatus("assetlocalize"))
        .containsExactlyInAnyOrder(
            new AsyncJobStatusCount(AsyncJobStatus.DONE, 1),
            new AsyncJobStatusCount(AsyncJobStatus.FAILED, 1),
            new AsyncJobStatusCount(AsyncJobStatus.QUEUED, 1));
    assertThat(jdbcAsyncJobStore.countByStatus("stats"))
        .containsExactly(new AsyncJobStatusCount(AsyncJobStatus.DONE, 1));

    assertThat(
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.FAILED, cutoffAfterCreatedRows, 10))
        .isEqualTo(1);
    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.FAILED, 10))
        .isEmpty();
  }

  @Test
  public void deleteTerminalJobsRejectsNonTerminalStatusAndHonorsLimit() {
    completeJob("assetlocalize", "{\"name\":\"done\"}");

    assertThat(
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.DONE, Instant.now().plusSeconds(1), 0))
        .isZero();
    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize", AsyncJobStatus.QUEUED, Instant.now().plusSeconds(1), 10));

    assertThat(jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.DONE, 10)).hasSize(1);
  }

  @Test
  public void storeMethodsRejectExcessiveLimits() {
    int excessiveLimit = AsyncJobQueueValidation.STORE_QUERY_LIMIT_MAX + 1;
    completeJob("assetlocalize", "{\"name\":\"done\"}");

    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.claimNextJobs(
                "assetlocalize", excessiveLimit, "worker-a", Duration.ofSeconds(5)));
    assertThrows(
        IllegalArgumentException.class,
        () -> jdbcAsyncJobStore.findByStatus("assetlocalize", AsyncJobStatus.DONE, excessiveLimit));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.deleteTerminalJobs(
                "assetlocalize",
                AsyncJobStatus.DONE,
                Instant.now().plusSeconds(1),
                excessiveLimit));
    assertThrows(IllegalArgumentException.class, () -> jdbcAsyncJobStore.getByIds(manyIds()));
  }

  @Test
  public void invalidNumericIdsFailFast() {
    assertThrows(
        IllegalArgumentException.class,
        () -> jdbcAsyncJobStore.getByIds(List.of(new AsyncJobId("abc"))));
  }

  @Test
  public void rejectsAvailableAtOutsideDatabaseTimestampBoundsBeforeJdbcWrite() {
    IllegalArgumentException tooEarly =
        assertThrows(
            IllegalArgumentException.class,
            () ->
                jdbcAsyncJobStore.enqueue(
                    "assetlocalize",
                    "{}",
                    AsyncJobQueueValidation.DATABASE_TIMESTAMP_MIN.minusNanos(1)));
    IllegalArgumentException tooLate =
        assertThrows(
            IllegalArgumentException.class,
            () ->
                jdbcAsyncJobStore.enqueue(
                    "assetlocalize",
                    "{}",
                    AsyncJobQueueValidation.DATABASE_TIMESTAMP_MAX.plusNanos(1)));

    assertThat(tooEarly).hasMessageContaining("availableAt must be between");
    assertThat(tooLate).hasMessageContaining("availableAt must be between");
  }

  @Test
  public void rejectsLeaseDurationOutsideDatabaseTimestampBoundsBeforeClaimWrite() {
    jdbcAsyncJobStore.enqueue("assetlocalize", "{}", Instant.now().minusSeconds(1));

    IllegalArgumentException exception =
        assertThrows(
            IllegalArgumentException.class,
            () ->
                jdbcAsyncJobStore.claimNextJobs(
                    "assetlocalize", 1, "worker-a", Duration.ofSeconds(Long.MAX_VALUE)));

    assertThat(exception).hasMessageContaining("leaseUntil");
  }

  @Test
  public void rejectsQueueNamesOutsideSchemaBounds() {
    assertThrows(
        IllegalArgumentException.class, () -> jdbcAsyncJobStore.enqueue(" ", "{}", Instant.now()));

    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.enqueue(
                "x".repeat(AsyncJobQueueValidation.QUEUE_NAME_MAX_LENGTH + 1),
                "{}",
                Instant.now()));
  }

  @Test
  public void rejectsWorkerIdsOutsideSchemaBounds() {
    jdbcAsyncJobStore.enqueue("assetlocalize", "{}", Instant.now().minusSeconds(1));

    assertThrows(
        IllegalArgumentException.class,
        () ->
            jdbcAsyncJobStore.claimNextJobs(
                "assetlocalize",
                1,
                "x".repeat(AsyncJobQueueValidation.WORKER_ID_MAX_LENGTH + 1),
                Duration.ofSeconds(1)));
  }

  private AsyncJobId completeJob(String queueName, String jobData) {
    AsyncJobId id = jdbcAsyncJobStore.enqueue(queueName, jobData, Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore.claimNextJobs(queueName, 1, "worker-a", Duration.ofSeconds(5)).get(0);
    assertThat(jdbcAsyncJobStore.markDone(queueName, id, "worker-a", claimed.leaseToken(), null))
        .isTrue();
    return id;
  }

  private AsyncJobId failJob(String queueName, String jobData) {
    AsyncJobId id = jdbcAsyncJobStore.enqueue(queueName, jobData, Instant.now().minusSeconds(1));
    AsyncJobRecord claimed =
        jdbcAsyncJobStore.claimNextJobs(queueName, 1, "worker-a", Duration.ofSeconds(5)).get(0);
    assertThat(
            jdbcAsyncJobStore.markFailed(
                queueName, id, "worker-a", claimed.leaseToken(), null, "boom"))
        .isTrue();
    return id;
  }

  private List<AsyncJobId> manyIds() {
    return java.util.stream.IntStream.rangeClosed(0, AsyncJobQueueValidation.STORE_QUERY_LIMIT_MAX)
        .mapToObj(index -> new AsyncJobId(String.valueOf(index + 1)))
        .toList();
  }

  private void assertSchemaViolation(String sql) {
    assertThrows(DataIntegrityViolationException.class, () -> jdbcTemplate.execute(sql));
  }

  private long statusCount(String queueName, AsyncJobStatus status) {
    return jdbcAsyncJobStore.countByStatus(queueName).stream()
        .filter(statusCount -> statusCount.status() == status)
        .mapToLong(AsyncJobStatusCount::count)
        .findFirst()
        .orElse(0);
  }

  private static class ClaimRaceNamedParameterJdbcTemplate extends NamedParameterJdbcTemplate {

    private final JdbcTemplate jdbcTemplate;
    private final AsyncJobId id;
    private final String raceSql;
    private final AtomicBoolean raceInjected = new AtomicBoolean();

    ClaimRaceNamedParameterJdbcTemplate(DataSource dataSource, AsyncJobId id, String raceSql) {
      super(dataSource);
      this.jdbcTemplate = new JdbcTemplate(dataSource);
      this.id = id;
      this.raceSql = raceSql;
    }

    @Override
    public <T> List<T> query(String sql, SqlParameterSource paramSource, RowMapper<T> rowMapper) {
      List<T> rows = super.query(sql, paramSource, rowMapper);
      if (!rows.isEmpty()
          && sql.equals(AsyncJobQueueJdbcDialect.HSQL.claimNextJobsSql())
          && raceInjected.compareAndSet(false, true)) {
        jdbcTemplate.update(raceSql, Long.parseLong(id.value()));
      }
      return rows;
    }
  }
}
