package com.box.l10n.mojito.service.review;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertNull;

import com.box.l10n.mojito.entity.review.ReviewAutomation;
import jakarta.persistence.EntityManager;
import jakarta.persistence.EntityManagerFactory;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import org.junit.Test;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.init.DatabasePopulatorUtils;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean;
import org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter;

public class ReviewAutomationLocalePersistenceTest {

  @Test
  public void migrationPreservesOldRowsAndExclusionsRemainAvailableAfterReloadAndDetach() {
    DriverManagerDataSource dataSource =
        new DriverManagerDataSource(
            "jdbc:hsqldb:mem:review-automation-locales-"
                + UUID.randomUUID()
                + ";sql.syntax_mys=true",
            "sa",
            "");
    JdbcTemplate jdbc = new JdbcTemplate(dataSource);
    // The pre-migration automation columns, without starting the application or its schedulers.
    jdbc.execute(
        """
        create table review_automation (
            id bigint generated by default as identity primary key,
            created_date timestamp, last_modified_date timestamp,
            name varchar(255) not null, enabled bit not null,
            cron_expression varchar(255) not null, time_zone varchar(100) not null,
            max_word_count_per_project int not null, due_date_offset_days int not null,
            assign_translator bit not null, team_id bigint
        )
        """);
    jdbc.update(
        """
        insert into review_automation (id, name, enabled, cron_expression, time_zone,
            max_word_count_per_project, due_date_offset_days, assign_translator)
        values (7, 'Legacy', true, '0 0 9 ? * MON-FRI', 'UTC', 2000, 1, true)
        """);
    DatabasePopulatorUtils.execute(
        new ResourceDatabasePopulator(
            new ClassPathResource("db/migration/V114__Review_Automation_Excluded_Locales.sql")),
        dataSource);
    assertNull(
        jdbc.queryForObject(
            "select excluded_locale_tags_json from review_automation where id = 7", String.class));

    LocalContainerEntityManagerFactoryBean factory = new LocalContainerEntityManagerFactoryBean();
    factory.setDataSource(dataSource);
    factory.setPackagesToScan("com.box.l10n.mojito.entity");
    factory.setJpaVendorAdapter(new HibernateJpaVendorAdapter());
    factory.setJpaPropertyMap(
        Map.of("hibernate.hbm2ddl.auto", "none", "hibernate.jdbc.time_zone", "UTC"));
    factory.afterPropertiesSet();
    try {
      EntityManagerFactory entityManagerFactory = factory.getObject();
      assertNotNull(entityManagerFactory);
      try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
        entityManager.getTransaction().begin();
        ReviewAutomation legacy = entityManager.find(ReviewAutomation.class, 7L);
        assertEquals("Legacy", legacy.getName());
        assertEquals(List.of(), legacy.getExcludedLocaleTags());
        legacy.setExcludedLocaleTags(List.of("he", "fr-FR"));
        entityManager.getTransaction().commit();
      }
      assertEquals(
          "[\"he\",\"fr-FR\"]",
          jdbc.queryForObject(
              "select excluded_locale_tags_json from review_automation where id = 7",
              String.class));

      ReviewAutomation detached;
      try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
        detached = entityManager.find(ReviewAutomation.class, 7L);
      }
      assertEquals(List.of("he", "fr-FR"), detached.getExcludedLocaleTags());

      try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
        entityManager.getTransaction().begin();
        entityManager.find(ReviewAutomation.class, 7L).setExcludedLocaleTags(List.of());
        entityManager.getTransaction().commit();
      }
      try (EntityManager entityManager = entityManagerFactory.createEntityManager()) {
        assertEquals(
            List.of(), entityManager.find(ReviewAutomation.class, 7L).getExcludedLocaleTags());
      }
    } finally {
      factory.destroy();
      jdbc.execute("shutdown");
    }
  }
}
