alter table review_project
    add column decided_word_count bigint not null default 0;

update review_project rp
set
    decided_count = coalesce(decided_word_counts.decided_count, 0),
    decided_word_count = coalesce(decided_word_counts.decided_word_count, 0)
from (
    select
        decided_units.review_project_id,
        count(*) as decided_count,
        coalesce(sum(coalesce(tu.word_count, 0)), 0) as decided_word_count
    from (
        select distinct
            rptu.id,
            rptu.review_project_id,
            rptu.tm_text_unit_id
        from review_project_text_unit rptu
        join review_project rp_inner
            on rp_inner.id = rptu.review_project_id
        left join review_project_text_unit_decision rptud
            on rptud.review_project_text_unit_id = rptu.id
        left join review_project_text_unit_feedback rptuf
            on rptuf.review_project_text_unit_id = rptu.id
        where (
            rp_inner.type in ('TERMINOLOGY', 'TERM_CANDIDATE')
            and rp_inner.terminology_phase = 'SPECIALIST_INPUT'
            and rptuf.id is not null
        ) or (
            not (
                rp_inner.type in ('TERMINOLOGY', 'TERM_CANDIDATE')
                and coalesce(rp_inner.terminology_phase, '') = 'SPECIALIST_INPUT'
            )
            and rptud.decision_state = 'DECIDED'
        )
    ) decided_units
    join tm_text_unit tu
        on tu.id = decided_units.tm_text_unit_id
    group by decided_units.review_project_id
) decided_word_counts
where decided_word_counts.review_project_id = rp.id;

update review_project rp
set
    decided_count = 0,
    decided_word_count = 0
where not exists (
    select 1
    from review_project_text_unit rptu
    join review_project rp_inner
        on rp_inner.id = rptu.review_project_id
    left join review_project_text_unit_decision rptud
        on rptud.review_project_text_unit_id = rptu.id
    left join review_project_text_unit_feedback rptuf
        on rptuf.review_project_text_unit_id = rptu.id
    where rptu.review_project_id = rp.id
        and (
            (
                rp_inner.type in ('TERMINOLOGY', 'TERM_CANDIDATE')
                and rp_inner.terminology_phase = 'SPECIALIST_INPUT'
                and rptuf.id is not null
            ) or (
                not (
                    rp_inner.type in ('TERMINOLOGY', 'TERM_CANDIDATE')
                    and coalesce(rp_inner.terminology_phase, '') = 'SPECIALIST_INPUT'
                )
                and rptud.decision_state = 'DECIDED'
            )
        )
);

alter table asset_integrity_checker
    drop constraint asset_integrity_checker_integrity_checker_type_check;

alter table asset_integrity_checker
    add constraint asset_integrity_checker_integrity_checker_type_check
        check (integrity_checker_type in (
            'MESSAGE_FORMAT',
            'FLUENT',
            'MESSAGE_FORMAT_DOUBLE_BRACES',
            'PRINTF_LIKE',
            'SIMPLE_PRINTF_LIKE',
            'PRINTF_LIKE_IGNORE_PERCENTAGE_AFTER_BRACKETS',
            'PRINTF_LIKE_VARIABLE_TYPE',
            'PRINTF_LIKE_ADD_PARAMETER_SPECIFIER',
            'COMPOSITE_FORMAT',
            'WHITESPACE',
            'TRAILING_WHITESPACE',
            'HTML_TAG',
            'FORMATJS_RICH_TEXT',
            'FORMATJS',
            'DOLLAR_TEMPLATE',
            'ELLIPSIS',
            'BACKQUOTE',
            'EMPTY_TARGET_NOT_EMPTY_SOURCE',
            'MARKDOWN_LINKS',
            'PYTHON_FPRINT',
            'EMAIL',
            'URL',
            'FORBIDS_CONTROL_CHARACTERS',
            'MISC_AI_TRANSLATE'
        ));

alter table asset_integrity_checker_aud
    drop constraint asset_integrity_checker_aud_integrity_checker_type_check;

alter table asset_integrity_checker_aud
    add constraint asset_integrity_checker_aud_integrity_checker_type_check
        check (integrity_checker_type in (
            'MESSAGE_FORMAT',
            'FLUENT',
            'MESSAGE_FORMAT_DOUBLE_BRACES',
            'PRINTF_LIKE',
            'SIMPLE_PRINTF_LIKE',
            'PRINTF_LIKE_IGNORE_PERCENTAGE_AFTER_BRACKETS',
            'PRINTF_LIKE_VARIABLE_TYPE',
            'PRINTF_LIKE_ADD_PARAMETER_SPECIFIER',
            'COMPOSITE_FORMAT',
            'WHITESPACE',
            'TRAILING_WHITESPACE',
            'HTML_TAG',
            'FORMATJS_RICH_TEXT',
            'FORMATJS',
            'DOLLAR_TEMPLATE',
            'ELLIPSIS',
            'BACKQUOTE',
            'EMPTY_TARGET_NOT_EMPTY_SOURCE',
            'MARKDOWN_LINKS',
            'PYTHON_FPRINT',
            'EMAIL',
            'URL',
            'FORBIDS_CONTROL_CHARACTERS',
            'MISC_AI_TRANSLATE'
        ));

create table review_project_assignment_window (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    review_project_id bigint not null,
    assigned_translator_user_id bigint default null,
    assigned_translator_username_snapshot varchar(255) default null,
    assigned_at timestamp(6) not null,
    accepted_at timestamp(6) default null,
    ended_at timestamp(6) default null,
    end_reason varchar(32) default null,
    self_reported_minutes integer default null,
    self_reported_note varchar(512) default null,
    self_reported_at timestamp(6) default null,
    self_reported_by_user_id bigint default null,
    primary key (id)
);

alter table review_project_assignment_window
    add constraint FK__RP_ASSIGNMENT_WINDOW__PROJECT
        foreign key (review_project_id) references review_project (id);

alter table review_project_assignment_window
    add constraint FK__RP_ASSIGNMENT_WINDOW__TRANSLATOR
        foreign key (assigned_translator_user_id) references "user" (id);

alter table review_project_assignment_window
    add constraint FK__RP_ASSIGNMENT_WINDOW__REPORTED_BY
        foreign key (self_reported_by_user_id) references "user" (id);

create index I__RP_ASSIGNMENT_WINDOW__PROJECT
    on review_project_assignment_window (review_project_id);

create index I__RP_ASSIGNMENT_WINDOW__TRANSLATOR
    on review_project_assignment_window (assigned_translator_user_id);

create index I__RP_ASSIGNMENT_WINDOW__ASSIGNED_AT
    on review_project_assignment_window (assigned_at);

create index I__RP_ASSIGNMENT_WINDOW__ACCEPTED_AT
    on review_project_assignment_window (accepted_at);

create index I__RP_ASSIGNMENT_WINDOW__ENDED_AT
    on review_project_assignment_window (ended_at);

create table review_project_time_spent_stat (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    assignment_window_id bigint not null,
    review_project_id bigint not null,
    review_project_request_id bigint default null,
    review_project_request_name varchar(255) default null,
    review_project_type varchar(32) default null,
    review_project_status varchar(32) default null,
    locale_bcp47_tag varchar(255) default null,
    assigned_translator_user_id bigint default null,
    assigned_translator_username varchar(255) default null,
    assignment_window_started_at timestamp(6) default null,
    assignment_accepted_at timestamp(6) default null,
    assignment_window_ended_at timestamp(6) default null,
    assignment_window_end_reason varchar(32) default null,
    project_created_date timestamp(6) default null,
    project_due_date timestamp(6) default null,
    text_unit_count bigint not null default 0,
    word_count bigint not null default 0,
    decided_count bigint not null default 0,
    decided_word_count bigint not null default 0,
    first_decision_at timestamp(6) default null,
    last_decision_at timestamp(6) default null,
    raw_decision_span_seconds bigint not null default 0,
    decision_interval_count bigint default null,
    rapid_decision_interval_count bigint default null,
    median_decision_interval_seconds bigint default null,
    p90_decision_interval_seconds bigint default null,
    p95_decision_interval_seconds bigint default null,
    project_span_seconds bigint not null default 0,
    accepted_to_first_decision_seconds bigint default null,
    assigned_to_accepted_seconds bigint default null,
    estimated_active_seconds bigint not null default 0,
    pause_seconds bigint not null default 0,
    pause_count bigint not null default 0,
    pause_ratio double precision not null default 0,
    self_reported_seconds bigint default null,
    reported_computed_delta_seconds bigint default null,
    reported_computed_ratio double precision default null,
    reported_missing boolean not null default false,
    review_flag varchar(32) not null default 'OK',
    closed_with_pending boolean not null default false,
    pending_count_at_close bigint default null,
    pending_word_count_at_close bigint default null,
    close_reason varchar(512) default null,
    finalized_at timestamp(6) default null,
    computed_at timestamp(6) not null,
    attribution_confidence varchar(32) not null default 'ASSIGNMENT_WINDOW',
    primary key (id)
);

alter table review_project_time_spent_stat
    add constraint FK__RP_TIME_SPENT_STAT__WINDOW
        foreign key (assignment_window_id) references review_project_assignment_window (id);

alter table review_project_time_spent_stat
    add constraint FK__RP_TIME_SPENT_STAT__PROJECT
        foreign key (review_project_id) references review_project (id);

alter table review_project_time_spent_stat
    add constraint FK__RP_TIME_SPENT_STAT__REQUEST
        foreign key (review_project_request_id) references review_project_request (id);

alter table review_project_time_spent_stat
    add constraint FK__RP_TIME_SPENT_STAT__TRANSLATOR
        foreign key (assigned_translator_user_id) references "user" (id);

create unique index UK__RP_TIME_SPENT_STAT__WINDOW
    on review_project_time_spent_stat (assignment_window_id);

create index I__RP_TIME_SPENT_STAT__PROJECT
    on review_project_time_spent_stat (review_project_id);

create index I__RP_TIME_SPENT_STAT__REQUEST
    on review_project_time_spent_stat (review_project_request_id);

create index I__RP_TIME_SPENT_STAT__TRANSLATOR
    on review_project_time_spent_stat (assigned_translator_user_id);

create index I__RP_TIME_SPENT_STAT__LOCALE
    on review_project_time_spent_stat (locale_bcp47_tag);

create index I__RP_TIME_SPENT_STAT__LAST_DECISION
    on review_project_time_spent_stat (last_decision_at);

create index I__RP_TIME_SPENT_STAT__FINALIZED
    on review_project_time_spent_stat (finalized_at);

create table json_config_localization (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    name varchar(255) not null,
    repository_id bigint not null,
    asset_path varchar(255) not null,
    provider varchar(32) not null default 'GENERIC_JSON',
    provider_config_id varchar(255) default null,
    schema_json text default null,
    source_config_json text default null,
    extraction_mapping_json text default null,
    output_locale_mapping_json text default null,
    automation_enabled boolean not null default false,
    automation_cron_expression varchar(255) default null,
    automation_time_zone varchar(128) default null,
    automation_options_json text default null,
    primary key (id)
);

alter table json_config_localization
    add constraint FK__JSON_CONFIG_LOCALIZATION__REPOSITORY
        foreign key (repository_id) references repository (id);

create index I__JSON_CONFIG_LOCALIZATION__REPOSITORY
    on json_config_localization (repository_id);

create unique index UK__JSON_CONFIG_LOCALIZATION__REPOSITORY_NAME
    on json_config_localization (repository_id, name);

create unique index UK__JSON_CONFIG_LOCALIZATION__REPOSITORY_ASSET_PATH
    on json_config_localization (repository_id, asset_path);

create index I__JSON_CONFIG_LOCALIZATION__NAME
    on json_config_localization (name);

create table json_config_localization_run (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    json_config_localization_id bigint not null,
    trigger_source varchar(32) not null,
    status varchar(32) not null,
    started_at timestamp(6) default null,
    finished_at timestamp(6) default null,
    pull_enabled boolean not null default false,
    extract_enabled boolean not null default false,
    translate_enabled boolean not null default false,
    merge_enabled boolean not null default false,
    save_config_enabled boolean not null default false,
    push_enabled boolean not null default false,
    pulled boolean not null default false,
    extracted boolean not null default false,
    translated boolean not null default false,
    merged boolean not null default false,
    saved_config boolean not null default false,
    pushed boolean not null default false,
    push_skipped boolean not null default false,
    summary varchar(1024) default null,
    error_message varchar(4000) default null,
    primary key (id)
);

alter table json_config_localization_run
    add constraint FK__JSON_CONFIG_LOCALIZATION_RUN__SETUP
        foreign key (json_config_localization_id) references json_config_localization (id);

create index I__JSON_CONFIG_LOCALIZATION_RUN__CREATED_DATE
    on json_config_localization_run (created_date);

create index I__JSON_CONFIG_LOCALIZATION_RUN__SETUP
    on json_config_localization_run (json_config_localization_id);

alter table branch
    add column cleanup_date timestamp(6) default null;

create index I__BRANCH__CLEANUP_DATE
    on branch (cleanup_date);

alter table ai_translate_automation_config
    add column excluded_repository_ids_json text;

create table review_project_text_unit_suggestion (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    review_project_text_unit_id bigint not null,
    source varchar(64) not null,
    target text not null,
    previous_target text default null,
    notes varchar(4000) default null,
    version bigint default 0,
    created_by_user_id bigint default null,
    last_modified_by_user_id bigint default null,
    primary key (id)
);

alter table review_project_text_unit_suggestion
    add constraint FK__RPTUS__REVIEW_PROJECT_TEXT_UNIT
        foreign key (review_project_text_unit_id) references review_project_text_unit (id);

alter table review_project_text_unit_suggestion
    add constraint FK__RPTUS__CREATED_BY_USER
        foreign key (created_by_user_id) references "user" (id);

alter table review_project_text_unit_suggestion
    add constraint FK__RPTUS__LAST_MODIFIED_BY_USER
        foreign key (last_modified_by_user_id) references "user" (id);

create unique index UK__REVIEW_PROJECT_TEXT_UNIT_SUGGESTION__TEXT_UNIT
    on review_project_text_unit_suggestion (review_project_text_unit_id);

create table mblob_cleanup_policy (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    prefix varchar(255) not null,
    enabled boolean not null default false,
    retention_days integer not null default 3,
    batch_size integer not null default 250,
    max_batches_per_run integer not null default 0,
    pause_millis integer not null default 250,
    max_retries integer not null default 5,
    stop_requested boolean not null default false,
    status varchar(32) not null default 'IDLE',
    last_started_date timestamp(6) default null,
    last_finished_date timestamp(6) default null,
    last_deleted_count bigint not null default 0,
    total_deleted_count bigint not null default 0,
    last_error varchar(2048) default null,
    primary key (id),
    constraint UK__MBLOB_CLEANUP_POLICY__PREFIX unique (prefix)
);

create index I__TTUCV__TM_MODIFIED
    on tm_text_unit_current_variant (tm_id, last_modified_date);

create index I__TTUCV__ASSET_LOCALE_MODIFIED
    on tm_text_unit_current_variant (asset_id, locale_id, last_modified_date);

create index I__RPTUD__STATE_MODIFIED_ID
    on review_project_text_unit_decision (decision_state, last_modified_date, id);

create table bulk_import_run (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    completed_date timestamp(6) default null,
    run_id varchar(36) not null,
    repository_id bigint not null,
    asset_id bigint not null,
    locale_id bigint not null,
    pollable_task_id bigint default null,
    initiating_user_id bigint default null,
    actor_type varchar(16) not null,
    actor_identity varchar(255) default null,
    source varchar(128) not null,
    import_mode varchar(32) not null,
    integrity_checks_type varchar(64) not null,
    status varchar(16) not null,
    requested_count integer not null,
    imported_count integer not null,
    skipped_count integer not null,
    input_payload_blob_name varchar(1024) default null,
    output_payload_blob_name varchar(1024) default null,
    error_message varchar(1024) default null,
    primary key (id)
);

alter table bulk_import_run
    add constraint FK__BULK_IMPORT_RUN__REPOSITORY
        foreign key (repository_id) references repository (id);

alter table bulk_import_run
    add constraint FK__BULK_IMPORT_RUN__ASSET
        foreign key (asset_id) references asset (id);

alter table bulk_import_run
    add constraint FK__BULK_IMPORT_RUN__LOCALE
        foreign key (locale_id) references locale (id);

alter table bulk_import_run
    add constraint FK__BULK_IMPORT_RUN__POLLABLE_TASK
        foreign key (pollable_task_id) references pollable_task (id);

alter table bulk_import_run
    add constraint FK__BULK_IMPORT_RUN__INITIATING_USER
        foreign key (initiating_user_id) references "user" (id);

create unique index UK__BULK_IMPORT_RUN__RUN_ID
    on bulk_import_run (run_id);

create index I__BULK_IMPORT_RUN__REPOSITORY_LOCALE
    on bulk_import_run (repository_id, locale_id, created_date);

create index I__BULK_IMPORT_RUN__POLLABLE_TASK
    on bulk_import_run (pollable_task_id);

alter table ai_translate_text_unit_attempt
    add column prompt_fingerprint varchar(64) default null,
    add column reasoning_effort varchar(32) default null,
    add column text_verbosity varchar(32) default null;

create index I__AITTA__EVALUATION_COHORT
    on ai_translate_text_unit_attempt (prompt_fingerprint, model, locale_id, created_date);

create table user_preferences (
    id bigint generated by default as identity (start with 1),
    created_date timestamp(6) default null,
    last_modified_date timestamp(6) default null,
    user_id bigint not null,
    preferences_json text not null,
    primary key (id)
);

alter table user_preferences
    add constraint FK__USER_PREFERENCES__USER__ID
        foreign key (user_id) references "user" (id) on delete cascade;

create unique index UK__USER_PREFERENCES__USER__ID
    on user_preferences (user_id);
