services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: mojito
      POSTGRES_USER: mojito
      POSTGRES_PASSWORD: ChangeMe
  webapp:
    depends_on:
      - db
    build:
      dockerfile: docker/Dockerfile-bk8
#      dockerfile: docker/Dockerfile-bk11
#      dockerfile: docker/Dockerfile-bk16
      context: ../
#    image: aurambaj/mojito-webapp-bk8:latest
    links:
      - db
    ports:
      - "8080:8080"
    restart: always
    environment:
#      JAVA_OPTS: '-Xms2g'
      SPRING_APPLICATION_JSON: '{
      "spring.profiles.active": "postgres",
      "spring.datasource.url" : "jdbc:postgresql://db:5432/mojito",
      "spring.datasource.username" : "mojito",
      "spring.datasource.password" : "ChangeMe"
      }'
