package com.box.l10n.mojito.service.oaireview;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertTrue;
import static org.mockito.ArgumentMatchers.anyString;
import static org.mockito.Mockito.doAnswer;
import static org.mockito.Mockito.doThrow;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.when;

import ch.qos.logback.classic.Level;
import ch.qos.logback.classic.Logger;
import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.Appender;
import ch.qos.logback.core.read.ListAppender;
import com.box.l10n.mojito.json.ObjectMapper;
import com.box.l10n.mojito.service.oaireview.AiReviewSubmissionRateObserver.Bucket;
import io.micrometer.core.instrument.MeterRegistry;
import io.micrometer.core.instrument.simple.SimpleMeterRegistry;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Proxy;
import java.nio.charset.StandardCharsets;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneOffset;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import java.util.concurrent.TimeUnit;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.concurrent.atomic.AtomicInteger;
import javax.sql.DataSource;
import org.hsqldb.jdbc.JDBCDataSource;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.DelegatingDataSource;

/** Real conditional SQL plus failures at the boundaries where diagnostics must stay optional. */
public class AiReviewSubmissionRateObserverTest {
  private static final Instant NOW = Instant.parse("2026-09-11T19:00:00Z");
  private final ObjectMapper mapper = ObjectMapper.withNoFailOnUnknownProperties();
  private final SimpleMeterRegistry metrics = new SimpleMeterRegistry();
  private final AiReviewSubmissionRateProperties configuration =
      new AiReviewSubmissionRateProperties();
  private final List<AiReviewSubmissionRateObserver> observers = new ArrayList<>();
  private JdbcTemplate jdbc;
  private DataSource source;
  private AiReviewSubmissionRateObserver observer;
  private Logger observerLogger;
  private Level previousLogLevel;
  private ListAppender<ILoggingEvent> logs;

  @Before
  public void setup() {
    JDBCDataSource database = new JDBCDataSource();
    database.setUrl("jdbc:hsqldb:mem:review_submission_" + UUID.randomUUID());
    database.setUser("SA");
    database.setPassword("");
    source = database;
    jdbc = new JdbcTemplate(source);
    jdbc.execute("SET DATABASE TRANSACTION CONTROL MVCC");
    jdbc.execute(
        "create table mblob (id bigint generated by default as identity primary key,"
            + " name varchar(255) unique, content blob not null, created_date timestamp)");
    observer = observer(source, metrics);
    observerLogger = (Logger) LoggerFactory.getLogger(AiReviewSubmissionRateObserver.class);
    previousLogLevel = observerLogger.getLevel();
    observerLogger.setLevel(Level.WARN);
    logs = new ListAppender<>();
    logs.start();
    observerLogger.addAppender(logs);
  }

  @After
  public void close() {
    observers.forEach(AiReviewSubmissionRateObserver::close);
    observerLogger.detachAppender(logs);
    observerLogger.setLevel(previousLogLevel);
    logs.stop();
    jdbc.execute("SHUTDOWN");
    metrics.close();
  }

  @Test
  public void tenImmediateSubmissionsFitAndFurtherSubmissionsOnlyRecordExcess() {
    submit(observer, 1, NOW, 10);
    assertEquals(10, count("within_allowance"), 0);
    assertEquals(0, count("excess"), 0);
    assertTrue(burstWarnings().isEmpty());
    submit(observer, 1, NOW, 5);
    assertEquals(5, count("excess"), 0);
    assertEquals(1, burstWarnings().size());
    assertEquals(0, bucket(1).tokens(), 0);
    String warning = burstWarnings().getFirst().getFormattedMessage();
    assertTrue(warning.contains("userId=1"));
    assertTrue(warning.contains("requestsPerSecond=3.0"));
    assertTrue(warning.contains("burstAllowance=10"));
    assertTrue(warning.contains("action=observe_only"));
  }

  @Test
  public void threeSubmissionsPerSecondRemainWithinAllowanceAfterInitialBurst() {
    submit(observer, 1, NOW, 10);
    for (int second = 1; second <= 20; second++) {
      submit(observer, 1, NOW.plusSeconds(second), 3);
    }
    assertEquals(70, count("within_allowance"), 0);
    assertEquals(0, count("excess"), 0);
    assertTrue(burstWarnings().isEmpty());
  }

  @Test
  public void excessDoesNotAccumulateDebtAndRefillIsCappedAtBurst() {
    submit(observer, 1, NOW, 30);
    assertEquals(0, bucket(1).tokens(), 0);
    submit(observer, 1, NOW.plusSeconds(1), 3);
    assertEquals(13, count("within_allowance"), 0);
    assertEquals(20, count("excess"), 0);
    submit(observer, 1, NOW.plusSeconds(20), 10);
    assertEquals(23, count("within_allowance"), 0);
    assertEquals(0, bucket(1).tokens(), 0);
    submit(observer, 1, NOW.plusSeconds(20), 1);
    assertEquals(21, count("excess"), 0);
  }

  @Test
  public void fourRequestsPerSecondPreservePartialRefillForThreeWithinAllowance() {
    submit(observer, 1, NOW, 10);
    for (int request = 1; request <= 40; request++) {
      observer.observeAt(1, NOW.plusMillis(request * 250L), 0);
    }
    assertEquals(40, count("within_allowance"), 0);
    assertEquals(10, count("excess"), 0);
    assertEquals(0, bucket(1).tokens(), 1e-9);
  }

  @Test
  public void separateInstancesShareEachUserButNeverOtherUsersAllowance() {
    AiReviewSubmissionRateObserver other = observer(source, metrics);
    submit(observer, 1, NOW, 5);
    submit(other, 1, NOW, 5);
    submit(other, 1, NOW, 1);
    submit(other, 2, NOW, 10);
    assertEquals(20, count("within_allowance"), 0);
    assertEquals(1, count("excess"), 0);
    assertEquals(0, bucket(1).tokens(), 0);
    assertEquals(0, bucket(2).tokens(), 0);
    assertEquals(2, jdbc.queryForObject("select count(*) from mblob", Integer.class).intValue());
  }

  @Test
  public void warningCooldownIsSharedAcrossInstancesAndDoesNotHideExcessCounts() {
    AiReviewSubmissionRateObserver other = observer(source, metrics);
    submit(observer, 1, NOW, 11);
    submit(other, 1, NOW.plusSeconds(1), 4);
    assertEquals(2, count("excess"), 0);
    assertEquals(1, burstWarnings().size());
    submit(other, 1, NOW.plusMillis(AiReviewSubmissionRateObserver.WARNING_INTERVAL_MILLIS), 11);
    assertEquals(3, count("excess"), 0);
    assertEquals(2, burstWarnings().size());
  }

  @Test
  public void oldOrDelayedSamplesDoNotConsumeTokensOrCreatePhantomBursts() {
    submit(observer, 1, NOW, 4);
    Bucket before = bucket(1);
    observer.observeAt(1, NOW.minusMillis(1), 0);
    observer.observeAt(1, NOW.plusSeconds(10), AiReviewSubmissionRateObserver.MAX_DELAY_MILLIS + 1);
    assertEquals(before, bucket(1));
    assertEquals(1, count("out_of_order"), 0);
    assertEquals(1, count("delayed"), 0);
    assertEquals(0, count("excess"), 0);
  }

  @Test
  public void requestPreparationDelayIsIncludedWithoutReassigningSubmissionTime() {
    ExecutorService inline = mock(ExecutorService.class);
    doAnswer(
            invocation -> {
              invocation.getArgument(0, Runnable.class).run();
              return null;
            })
        .when(inline)
        .execute(org.mockito.ArgumentMatchers.any());
    AiReviewSubmissionRateObserver delayed =
        new AiReviewSubmissionRateObserver(
            configuration,
            mapper,
            jdbc,
            new DataSourceTransactionManager(source),
            metrics,
            Clock.fixed(NOW.plusSeconds(3), ZoneOffset.UTC),
            inline);
    observers.add(delayed);
    delayed.observe(1L, NOW, System.nanoTime() - TimeUnit.SECONDS.toNanos(3));
    assertEquals(1, count("delayed"), 0);
    assertEquals(0, jdbc.queryForObject("select count(*) from mblob", Integer.class).intValue());
    assertTrue(burstWarnings().isEmpty());
  }

  @Test
  public void compareAndSetConflictRereadsAndPreservesTheCompetingSubmission() {
    submit(observer, 1, NOW, 1);
    AtomicBoolean first = new AtomicBoolean(true);
    AtomicInteger updates = new AtomicInteger();
    DataSource competing =
        interceptWrites(
            sql -> {
              if (sql.startsWith("update mblob")) {
                updates.incrementAndGet();
                if (first.getAndSet(false)) submit(observer, 1, NOW, 1);
              }
              return false;
            });
    observer(competing, metrics).observeAt(1, NOW, 0);
    assertEquals(2, updates.get());
    assertEquals(7, bucket(1).tokens(), 0);
    assertEquals(3, count("within_allowance"), 0);
    assertEquals(0, count("contended"), 0);
  }

  @Test
  public void competingFirstInsertRetainsBothSubmissionsInOneRow() {
    AtomicBoolean first = new AtomicBoolean(true);
    DataSource competing =
        interceptWrites(
            sql -> {
              if (sql.startsWith("insert into mblob") && first.getAndSet(false)) {
                submit(observer, 1, NOW, 1);
              }
              return false;
            });
    observer(competing, metrics).observeAt(1, NOW, 0);
    assertEquals(8, bucket(1).tokens(), 0);
    assertEquals(2, count("within_allowance"), 0);
    assertEquals(1, jdbc.queryForObject("select count(*) from mblob", Integer.class).intValue());
  }

  @Test
  public void exhaustedCompareAndSetAttemptsDropOnlyTheObservation() {
    submit(observer, 1, NOW, 1);
    AtomicInteger updates = new AtomicInteger();
    DataSource contended =
        interceptWrites(
            sql -> {
              if (sql.startsWith("update mblob")) {
                updates.incrementAndGet();
                return true;
              }
              return false;
            });
    observer(contended, metrics).observeAt(1, NOW, 0);
    assertEquals(3, updates.get());
    assertEquals(9, bucket(1).tokens(), 0);
    assertEquals(1, count("contended"), 0);
    assertEquals(0, count("excess"), 0);
  }

  @Test
  public void onlyCommittedWinnerWarnsWhenAnExcessObservationLosesItsFirstCas() {
    submit(observer, 1, NOW, 10);
    AtomicBoolean first = new AtomicBoolean(true);
    DataSource competing =
        interceptWrites(
            sql -> {
              if (sql.startsWith("update mblob") && first.getAndSet(false)) {
                observer.observeAt(1, NOW, 0);
              }
              return false;
            });
    observer(competing, metrics).observeAt(1, NOW, 0);
    assertEquals(2, count("excess"), 0);
    assertEquals(1, burstWarnings().size());
    assertEquals(NOW.toEpochMilli(), bucket(1).lastWarningMillis());
  }

  @Test
  public void observationThatAgesDuringAConflictingWriteDoesNotRetryWithFreshTimestamp() {
    submit(observer, 1, NOW, 1);
    AtomicInteger updates = new AtomicInteger();
    DataSource slow =
        interceptWrites(
            sql -> {
              if (sql.startsWith("update mblob")) {
                updates.incrementAndGet();
                try {
                  TimeUnit.MILLISECONDS.sleep(AiReviewSubmissionRateObserver.MAX_DELAY_MILLIS + 30);
                } catch (InterruptedException interrupted) {
                  Thread.currentThread().interrupt();
                  throw new IllegalStateException(interrupted);
                }
                return true;
              }
              return false;
            });
    observer(slow, metrics).observeAt(1, NOW, 0);
    assertEquals(1, updates.get());
    assertEquals(1, count("delayed"), 0);
    assertEquals(0, count("contended"), 0);
    assertEquals(9, bucket(1).tokens(), 0);
    assertEquals(NOW.toEpochMilli(), bucket(1).updatedAtMillis());
  }

  @Test
  public void databaseFailureAndMalformedStateNeverEscapeObservation() throws Exception {
    DataSource unavailable = mock(DataSource.class);
    when(unavailable.getConnection()).thenThrow(new SQLException("unavailable"));
    observer(unavailable, metrics).observeAt(1, NOW, 0);
    assertEquals(1, count("unavailable"), 0);
    jdbc.update(
        "insert into mblob (name, content, created_date) values (?, ?, CURRENT_TIMESTAMP)",
        AiReviewSubmissionRateObserver.PREFIX + 1,
        "broken-json".getBytes(StandardCharsets.UTF_8));
    observer.observeAt(1, NOW, 0);
    assertEquals(2, count("unavailable"), 0);
    assertEquals(0, count("excess"), 0);
  }

  @Test
  @SuppressWarnings("unchecked")
  public void failedMetricsAndLoggerDoNotEscapeOrUndoCommittedObservation() {
    MeterRegistry brokenMetrics = mock(MeterRegistry.class);
    when(brokenMetrics.counter(anyString(), anyString(), anyString()))
        .thenThrow(new IllegalStateException("metrics unavailable"));
    Appender<ILoggingEvent> brokenAppender = mock(Appender.class);
    doThrow(new IllegalStateException("logger unavailable"))
        .when(brokenAppender)
        .doAppend(org.mockito.ArgumentMatchers.any());
    observerLogger.addAppender(brokenAppender);
    try {
      submit(observer(source, brokenMetrics), 1, NOW, 11);
      assertEquals(0, bucket(1).tokens(), 0);
      assertEquals(NOW.toEpochMilli(), bucket(1).lastWarningMillis());
    } finally {
      observerLogger.detachAppender(brokenAppender);
    }
  }

  @Test
  public void disabledAndMissingUserObservationsNeverReachDatabase() {
    configuration.setEnabled(false);
    observer.observe(1L);
    configuration.setEnabled(true);
    observer.observe(null);
    observer.observe(0L);
    observer.observe(-1L);
    assertEquals(3, count("missing_user"), 0);
    assertEquals(0, jdbc.queryForObject("select count(*) from mblob", Integer.class).intValue());
  }

  @Test
  public void metricLabelsContainOnlyFixedOutcomesAndNeverUserIdentifiers() {
    submit(observer, 1234567, NOW, 11);
    assertFalse(metrics.getMeters().isEmpty());
    metrics
        .getMeters()
        .forEach(
            meter -> {
              assertEquals(1, meter.getId().getTags().size());
              assertEquals("outcome", meter.getId().getTags().getFirst().getKey());
              assertFalse(meter.getId().toString().contains("1234567"));
            });
  }

  @Test
  public void blockedObserverWorkerAndFullQueueNeverRunDatabaseWorkOnCaller() throws Exception {
    CountDownLatch enteredDatabase = new CountDownLatch(1);
    CountDownLatch releaseDatabase = new CountDownLatch(1);
    CountDownLatch databaseReturned = new CountDownLatch(1);
    DataSource blocked =
        new DelegatingDataSource(source) {
          @Override
          public Connection getConnection() throws SQLException {
            enteredDatabase.countDown();
            try {
              if (!releaseDatabase.await(5, TimeUnit.SECONDS)) {
                throw new SQLException("test database wait expired");
              }
              return super.getConnection();
            } catch (InterruptedException interrupted) {
              Thread.currentThread().interrupt();
              throw new SQLException("observer stopped", interrupted);
            } finally {
              databaseReturned.countDown();
            }
          }
        };
    AiReviewSubmissionRateObserver async =
        new AiReviewSubmissionRateObserver(
            configuration,
            mapper,
            new JdbcTemplate(blocked),
            new DataSourceTransactionManager(blocked),
            metrics);
    observers.add(async);
    ExecutorService caller = Executors.newSingleThreadExecutor();
    try {
      async.observe(1L);
      assertTrue(enteredDatabase.await(2, TimeUnit.SECONDS));
      caller
          .submit(
              () -> {
                for (int i = 0; i < 300; i++) async.observe(1L);
              })
          .get(1, TimeUnit.SECONDS);
      // The request path records drops in memory; reporting them is deferred off that path.
      async.close();
      assertEquals(44, count("overloaded"), 0);
      assertEquals(1, releaseDatabase.getCount());
      assertEquals(0, jdbc.queryForObject("select count(*) from mblob", Integer.class).intValue());
    } finally {
      async.close();
      releaseDatabase.countDown();
      assertTrue(databaseReturned.await(2, TimeUnit.SECONDS));
      caller.shutdownNow();
    }
  }

  private AiReviewSubmissionRateObserver observer(DataSource dataSource, MeterRegistry registry) {
    AiReviewSubmissionRateObserver result =
        new AiReviewSubmissionRateObserver(
            configuration,
            mapper,
            new JdbcTemplate(dataSource),
            new DataSourceTransactionManager(dataSource),
            registry,
            Clock.fixed(NOW, ZoneOffset.UTC),
            mock(ExecutorService.class));
    observers.add(result);
    return result;
  }

  private static void submit(
      AiReviewSubmissionRateObserver target, long userId, Instant submittedAt, int count) {
    for (int i = 0; i < count; i++) target.observeAt(userId, submittedAt, 0);
  }

  private Bucket bucket(long userId) {
    byte[] content =
        jdbc.queryForObject(
            "select content from mblob where name = ?",
            byte[].class,
            AiReviewSubmissionRateObserver.PREFIX + userId);
    return mapper.readValueUnchecked(new String(content, StandardCharsets.UTF_8), Bucket.class);
  }

  private double count(String outcome) {
    var counter = metrics.find("AiReviewSubmission.observation").tag("outcome", outcome).counter();
    return counter == null ? 0 : counter.count();
  }

  private List<ILoggingEvent> burstWarnings() {
    return logs.list.stream()
        .filter(
            event -> event.getFormattedMessage().startsWith("AI review submission burst observed"))
        .toList();
  }

  /** A real competing write between SELECT and UPDATE exercises the CAS predicate itself. */
  private DataSource interceptWrites(WriteInterception interception) {
    return new DelegatingDataSource(source) {
      @Override
      public Connection getConnection() throws SQLException {
        Connection connection = super.getConnection();
        return (Connection)
            Proxy.newProxyInstance(
                getClass().getClassLoader(),
                new Class<?>[] {Connection.class},
                (proxy, method, arguments) -> {
                  try {
                    Object result = method.invoke(connection, arguments);
                    if (method.getName().equals("prepareStatement")) {
                      String sql = (String) arguments[0];
                      PreparedStatement statement = (PreparedStatement) result;
                      return Proxy.newProxyInstance(
                          getClass().getClassLoader(),
                          new Class<?>[] {PreparedStatement.class},
                          (statementProxy, statementMethod, statementArguments) -> {
                            if (statementMethod.getName().equals("executeUpdate")
                                && interception.skip(sql)) return 0;
                            try {
                              return statementMethod.invoke(statement, statementArguments);
                            } catch (InvocationTargetException failure) {
                              throw failure.getCause();
                            }
                          });
                    }
                    return result;
                  } catch (InvocationTargetException failure) {
                    throw failure.getCause();
                  }
                });
      }
    };
  }

  private interface WriteInterception {
    boolean skip(String sql);
  }
}
