package com.box.l10n.mojito.service.blobstorage.migration;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.box.l10n.mojito.quartz.QuartzSchedulerManager;
import com.box.l10n.mojito.service.blobstorage.azure.AzureBlobStorage;
import com.box.l10n.mojito.service.blobstorage.migration.BlobMigrationStore.Run;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.mockito.ArgumentCaptor;
import org.quartz.JobDataMap;
import org.quartz.JobExecutionContext;
import org.quartz.JobKey;
import org.quartz.Scheduler;
import org.quartz.Trigger;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;

public class BlobMigrationServiceTest {
  EmbeddedDatabase database;
  JdbcTemplate jdbc;
  BlobMigrationStore store;
  BlobMigrationProperties properties;
  AzureBlobStorage azure;
  BlobMigrationService service;
  QuartzSchedulerManager schedulers;
  Scheduler scheduler;
  Map<String, byte[]> objects;

  @Before
  @SuppressWarnings("unchecked")
  public void setup() throws Exception {
    database =
        new EmbeddedDatabaseBuilder()
            .generateUniqueName(true)
            .setType(EmbeddedDatabaseType.HSQL)
            .build();
    jdbc = new JdbcTemplate(database);
    jdbc.execute("set database sql syntax mys true");
    jdbc.execute(
        "create table mblob (id bigint generated by default as identity primary key, name varchar(255), content varbinary(1048576), created_date timestamp(6), expire_after_seconds bigint)");
    // Same production migration and indexes, with only HSQL's spelling of these two types.
    String ddl =
        new ClassPathResource("db/migration/V121__MBlob_Migration.sql")
            .getContentAsString(StandardCharsets.UTF_8)
            .replace("datetime(6)", "timestamp(6)")
            .replace(" bit ", " boolean ");
    new ResourceDatabasePopulator(new ByteArrayResource(ddl.getBytes(StandardCharsets.UTF_8)))
        .execute(database);
    store = new BlobMigrationStore(jdbc, new DataSourceTransactionManager(database));
    properties = new BlobMigrationProperties();
    properties.setEnabled(true);
    azure = mock(AzureBlobStorage.class);
    when(azure.getTargetDescription(anyString()))
        .thenAnswer(
            call -> "https://example.blob.core.windows.net/container/root/" + call.getArgument(0));
    ObjectProvider<AzureBlobStorage> provider = mock(ObjectProvider.class);
    when(provider.getIfAvailable()).thenReturn(azure);
    schedulers = mock(QuartzSchedulerManager.class);
    scheduler = mock(Scheduler.class);
    when(schedulers.getScheduler(QuartzSchedulerManager.DEFAULT_SCHEDULER_NAME))
        .thenReturn(scheduler);
    service = new BlobMigrationService(store, properties, provider, schedulers);
    objects = new HashMap<>();
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenAnswer(
            call ->
                objects.putIfAbsent(call.getArgument(0), ((byte[]) call.getArgument(1)).clone())
                    == null);
    when(azure.getSnapshotBytes(anyString(), anyInt()))
        .thenAnswer(
            call -> {
              byte[] value = objects.get(call.getArgument(0));
              if (value == null || value.length != (int) call.getArgument(1))
                throw new AzureBlobStorage.SnapshotVerificationException();
              return value.clone();
            });
  }

  @After
  public void close() {
    if (database != null) database.shutdown();
  }

  @Test
  public void disabledByDefaultAndCannotCreateOrRun() {
    BlobMigrationProperties defaults = new BlobMigrationProperties();
    assertFalse(defaults.isEnabled());
    properties.setEnabled(false);
    assertThrows(IllegalStateException.class, () -> service.create(request(10, 1000)));
    assertThrows(IllegalStateException.class, () -> service.runBatch("unused"));
    service.runRequested();
    verifyNoInteractions(azure);
    assertTrue(store.list().isEmpty());
  }

  @Test
  public void persistedRecurringTriggerCannotRunManualOnlySnapshotWorker() {
    insert(1, "clob_storage_ws/example", new byte[] {1}, null);
    Run run = start(1, 1000);
    clearInvocations(azure);
    job(false).execute(context(new JobDataMap()));
    assertEquals(0, store.get(run.id()).cursorId());
    assertTrue(objects.isEmpty());
    verifyNoInteractions(azure);
  }

  @Test
  public void disabledSnapshotWorkerIgnoresPersistedRecurringAndManualTriggers() {
    insert(1, "clob_storage_ws/example", new byte[] {1}, null);
    Run run = start(1, 1000);
    JobDataMap manual = new JobDataMap();
    manual.put(BlobMigrationJob.MANUAL_RUN_ID, run.id());
    properties.setEnabled(false);
    clearInvocations(azure);
    job(true).execute(context(new JobDataMap()));
    job(false).execute(context(manual));
    assertEquals(0, store.get(run.id()).cursorId());
    assertTrue(objects.isEmpty());
    verifyNoInteractions(azure);
  }

  @Test
  public void explicitlyEnabledRecurringTriggerRunsOneBoundedSnapshotBatch() {
    insert(1, "clob_storage_ws/first", new byte[] {1}, null);
    insert(2, "clob_storage_ws/second", new byte[] {2}, null);
    Run run = start(1, 1000);
    job(true).execute(context(new JobDataMap()));
    assertEquals(1, store.get(run.id()).cursorId());
    assertEquals(1, store.get(run.id()).verified());
    assertEquals(1, objects.size());
  }

  @Test
  public void manualResumeTargetsSelectedRunAndStillHonorsPause() throws Exception {
    insert(1, "clob_storage_ws/first", new byte[] {1}, null);
    insert(2, "clob_storage_ws/second", new byte[] {2}, null);
    Run first = start(1, 1000);
    Run second = start(1, 1000);
    String ordinarilySelected = store.ready().getFirst();
    String selected = ordinarilySelected.equals(first.id()) ? second.id() : first.id();
    service.resume(selected);
    ArgumentCaptor<JobDataMap> data = ArgumentCaptor.forClass(JobDataMap.class);
    verify(scheduler)
        .triggerJob(eq(JobKey.jobKey(BlobMigrationJobConfiguration.JOB_NAME)), data.capture());
    assertEquals(selected, data.getValue().getString(BlobMigrationJob.MANUAL_RUN_ID));
    BlobMigrationJob manual = job(false);
    manual.execute(context(data.getValue()));
    assertEquals(1, store.get(selected).cursorId());
    assertEquals(0, store.get(ordinarilySelected).cursorId());
    assertEquals(1, objects.size());
    service.pause(selected);
    manual.execute(context(data.getValue()));
    assertEquals(1, store.get(selected).cursorId());
    assertEquals(0, store.get(ordinarilySelected).cursorId());
    assertEquals(1, objects.size());
  }

  @Test
  public void invalidManualRunMarkerCannotFallBackToRecurringSelection() {
    insert(1, "clob_storage_ws/example", new byte[] {1}, null);
    Run run = start(1, 1000);
    JobDataMap invalid = new JobDataMap();
    invalid.put(BlobMigrationJob.MANUAL_RUN_ID, " ");
    assertThrows(IllegalArgumentException.class, () -> job(true).execute(context(invalid)));
    assertEquals(0, store.get(run.id()).cursorId());
    assertTrue(objects.isEmpty());
  }

  private BlobMigrationJob job(boolean recurring) {
    BlobMigrationJob job = new BlobMigrationJob();
    job.service = service;
    job.properties = properties;
    job.schedulingEnabled = recurring;
    return job;
  }

  private JobExecutionContext context(JobDataMap data) {
    Trigger trigger = mock(Trigger.class);
    when(trigger.getJobDataMap()).thenReturn(data);
    JobExecutionContext context = mock(JobExecutionContext.class);
    when(context.getTrigger()).thenReturn(trigger);
    return context;
  }

  @Test
  public void copiesBinaryWithoutChangingSourceOrCanonicalNamespace() {
    byte[] bytes = new byte[] {0, -1, 13, 10, 67};
    insert(1, "clob_storage_ws/example", bytes, 86400L);
    Run run = start(10, 1000);
    service.runBatch(run.id());
    var evidence = store.evidence(run.id(), 0, 10).getFirst();
    assertEquals("VERIFIED_SNAPSHOT", evidence.disposition());
    assertEquals(BlobMigrationService.sha256(bytes), evidence.digest());
    assertEquals(Long.valueOf(86400), evidence.expireSeconds());
    assertNotNull(evidence.createdDate());
    assertNotNull(evidence.verifiedAt());
    assertTrue(evidence.snapshotName().startsWith("mblob_migration/v1/" + run.id() + "/1/"));
    assertArrayEquals(bytes, objects.get(evidence.snapshotName()));
    assertArrayEquals(
        bytes, jdbc.queryForObject("select content from mblob where id = 1", byte[].class));
    assertFalse(objects.containsKey("clob_storage_ws/example"));
    Run complete = store.get(run.id());
    assertEquals("SNAPSHOT_COMPLETE", complete.status());
    assertEquals(1, complete.verified());
    assertEquals(bytes.length, complete.verifiedBytes());
    assertThrows(IllegalArgumentException.class, () -> store.request(run.id(), true));
  }

  @Test
  public void boundsRowsBytesAndHighWaterAndResumesWithoutRescanning() {
    insert(1, "clob_storage_ws/a", bytes("abc"), null);
    insert(2, "clob_storage_ws/b", bytes("def"), null);
    Run run = start(10, 5);
    insert(3, "clob_storage_ws/after-boundary", bytes("ghi"), null);
    service.runBatch(run.id());
    assertEquals(1, store.get(run.id()).cursorId());
    assertEquals("READY", store.get(run.id()).status());
    service.runBatch(run.id());
    assertEquals("SNAPSHOT_COMPLETE", store.get(run.id()).status());
    assertEquals(2, store.get(run.id()).scanned());
    assertEquals(6, store.get(run.id()).verifiedBytes());
    assertEquals(2, objects.size());
    verify(azure, times(2)).createSnapshotIfAbsent(anyString(), any(byte[].class));
  }

  @Test
  public void oneRowBudgetIncludesPreservedRows() {
    insert(1, "unknown/a", bytes("a"), null);
    insert(2, "clob_storage_ws/b", bytes("b"), null);
    Run run = start(1, 100);
    service.runBatch(run.id());
    assertEquals(1, store.get(run.id()).scanned());
    assertTrue(objects.isEmpty());
    service.runBatch(run.id());
    assertEquals(2, store.get(run.id()).scanned());
    assertEquals("SNAPSHOT_COMPLETE", store.get(run.id()).status());
  }

  @Test
  public void preservesUnknownControlUnselectedNullAndOversizedRows() {
    insert(1, "unknown/keep", bytes("a"), null);
    insert(2, "ai_review_execution/v1/capacity", bytes("a"), null);
    insert(3, "ai_review_submission_rate/v1/user/1", bytes("a"), null);
    insert(4, "multi_branch_state/keep", bytes("a"), null);
    insert(5, "clob_storage_ws/null", null, null);
    insert(6, "clob_storage_ws/large", bytes("oversized"), null);
    Run run = start(10, 5);
    service.runBatch(run.id());
    assertEquals(
        List.of(
            "PRESERVED_UNKNOWN",
            "PRESERVED_CONTROL",
            "PRESERVED_CONTROL",
            "PRESERVED_NOT_SELECTED",
            "PRESERVED_NULL",
            "PRESERVED_OVERSIZE"),
        store.evidence(run.id(), 0, 10).stream()
            .map(BlobMigrationStore.Evidence::disposition)
            .toList());
    assertEquals(6, store.get(run.id()).preserved());
    assertEquals(6, (long) jdbc.queryForObject("select count(*) from mblob", Long.class));
    verify(azure, never()).createSnapshotIfAbsent(anyString(), any(byte[].class));
  }

  @Test
  public void continuesPastFailureAndRetriesDurablyWithAccurateCounters() {
    insert(1, "clob_storage_ws/a", bytes("a"), null);
    insert(2, "clob_storage_ws/b", bytes("b"), null);
    AtomicBoolean fail = new AtomicBoolean(true);
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenAnswer(
            call -> {
              if (((String) call.getArgument(0)).contains("/1/") && fail.getAndSet(false))
                throw new IllegalStateException("secret provider URL must not be recorded");
              return objects.putIfAbsent(
                      call.getArgument(0), ((byte[]) call.getArgument(1)).clone())
                  == null;
            });
    Run run = start(10, 100);
    service.runBatch(run.id());
    assertEquals(2, store.get(run.id()).cursorId());
    assertEquals(1, store.get(run.id()).failed());
    assertEquals("IllegalStateException", store.evidence(run.id(), 0, 10).getFirst().error());
    service.runBatch(run.id());
    assertEquals("SNAPSHOT_COMPLETE", store.get(run.id()).status());
    assertEquals(2, store.get(run.id()).verified());
    assertEquals(2, store.get(run.id()).scanned());
    assertEquals(0, store.get(run.id()).failed());
    assertEquals(2, store.evidence(run.id(), 0, 10).getFirst().attempts());
  }

  @Test
  public void exhaustedFailuresRemainVisibleAndDoNotHoldTheCursor() {
    insert(1, "clob_storage_ws/a", bytes("a"), null);
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenThrow(new IllegalStateException());
    Run run = start(10, 100);
    for (int i = 0; i < 3; i++) service.runBatch(run.id());
    assertEquals("SNAPSHOT_WITH_FAILURES", store.get(run.id()).status());
    assertEquals(1, store.get(run.id()).failed());
    assertEquals(3, store.evidence(run.id(), 0, 10).getFirst().attempts());
    assertEquals(1, store.get(run.id()).cursorId());
  }

  @Test
  public void verificationMismatchPausesAndNeverOverwritesExistingObject() {
    insert(1, "clob_storage_ws/a", bytes("a"), null);
    Run run = start(10, 100);
    String target =
        BlobMigrationService.SNAPSHOT_PREFIX
            + run.id()
            + "/1/"
            + BlobMigrationService.sha256(bytes("a"));
    objects.put(target, bytes("b"));
    service.runBatch(run.id());
    assertEquals("PAUSED", store.get(run.id()).status());
    assertEquals("VERIFICATION_FAILED", store.get(run.id()).lastError());
    assertArrayEquals(bytes("b"), objects.get(target));
    assertEquals(0, store.get(run.id()).verified());
    assertEquals(1, store.get(run.id()).failed());
  }

  @Test
  public void concurrentSourceMutationIsPreservedAndNotVerifiedAsCurrent() {
    insert(1, "clob_storage_ws/a", bytes("old"), null);
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenAnswer(
            call -> {
              objects.put(call.getArgument(0), ((byte[]) call.getArgument(1)).clone());
              jdbc.update("update mblob set content = ? where id = 1", bytes("new"));
              return true;
            });
    Run run = start(10, 100);
    service.runBatch(run.id());
    var evidence = store.evidence(run.id(), 0, 10).getFirst();
    assertEquals("SOURCE_CHANGED", evidence.disposition());
    assertNotNull(evidence.verifiedAt());
    assertArrayEquals(bytes("old"), objects.get(evidence.snapshotName()));
    assertArrayEquals(
        bytes("new"), jdbc.queryForObject("select content from mblob where id = 1", byte[].class));
    assertEquals(0, store.get(run.id()).verified());
  }

  @Test
  public void concurrentSourceDeletionCannotResurrectCanonicalObject() {
    insert(1, "clob_storage_ws/a", bytes("old"), null);
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenAnswer(
            call -> {
              objects.put(call.getArgument(0), ((byte[]) call.getArgument(1)).clone());
              jdbc.update("delete from mblob where id = 1");
              return true;
            });
    Run run = start(10, 100);
    service.runBatch(run.id());
    assertEquals("SOURCE_CHANGED", store.evidence(run.id(), 0, 10).getFirst().disposition());
    assertFalse(objects.containsKey("clob_storage_ws/a"));
  }

  @Test
  public void pauseFencesInFlightWorkerAndRetryVerifiesExistingSnapshot() {
    insert(1, "clob_storage_ws/a", bytes("a"), null);
    Run run = start(10, 100);
    AtomicBoolean pause = new AtomicBoolean(true);
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenAnswer(
            call -> {
              boolean created =
                  objects.putIfAbsent(call.getArgument(0), ((byte[]) call.getArgument(1)).clone())
                      == null;
              if (pause.getAndSet(false)) store.request(run.id(), false);
              return created;
            });
    service.runBatch(run.id());
    assertEquals("PAUSED", store.get(run.id()).status());
    assertEquals(0, store.get(run.id()).cursorId());
    assertTrue(store.evidence(run.id(), 0, 10).isEmpty());
    assertEquals(1, objects.size());
    store.request(run.id(), true);
    service.runBatch(run.id());
    assertEquals(1, store.get(run.id()).verified());
    assertEquals(1, objects.size());
  }

  @Test
  public void leaseTakeoverRejectsOldWorkersAndParallelClaim() {
    Run run = start(10, 100);
    String old = store.claim(run.id(), 60);
    assertNotNull(old);
    assertNull(store.claim(run.id(), 60));
    jdbc.update(
        "update mblob_migration_run set lease_until = ? where id = ?",
        Timestamp.from(Instant.now().minusSeconds(60)),
        run.id());
    String next = store.claim(run.id(), 60);
    assertNotNull(next);
    assertNotEquals(old, next);
    assertThrows(BlobMigrationStore.LeaseLost.class, () -> store.renew(run.id(), old, 60));
    assertThrows(
        BlobMigrationStore.LeaseLost.class,
        () -> store.release(run.id(), old, "SNAPSHOT_COMPLETE", null));
    assertEquals(next, store.get(run.id()).leaseToken());
  }

  @Test
  public void refusesDestinationChangeAcrossResume() {
    insert(1, "clob_storage_ws/a", bytes("a"), null);
    Run run = start(10, 100);
    when(azure.getTargetDescription(anyString()))
        .thenReturn("https://different.blob.core.windows.net/elsewhere");
    assertThrows(IllegalStateException.class, () -> service.runBatch(run.id()));
    assertEquals(0, store.get(run.id()).cursorId());
    verify(azure, never()).createSnapshotIfAbsent(anyString(), any(byte[].class));
  }

  @Test
  public void rejectsUnsafeScopeAndBounds() {
    assertThrows(
        IllegalArgumentException.class,
        () ->
            service.create(new BlobMigrationService.CreateRequest(List.of("unknown"), 1, 1, 1, 1)));
    assertThrows(
        IllegalArgumentException.class,
        () ->
            service.create(
                new BlobMigrationService.CreateRequest(List.of("clob_storage_ws/"), 1, 1, 1, 1)));
    assertThrows(IllegalArgumentException.class, () -> service.create(request(0, 100)));
    assertThrows(IllegalArgumentException.class, () -> service.create(request(1, 268435457)));
    assertThrows(IllegalArgumentException.class, () -> service.evidence("x", 0, 1001));
    assertTrue(store.list().isEmpty());
  }

  Run start(int rows, long bytes) {
    Run run = service.create(request(rows, bytes));
    return store.request(run.id(), true);
  }

  BlobMigrationService.CreateRequest request(int rows, long bytes) {
    return new BlobMigrationService.CreateRequest(List.of("clob_storage_ws"), rows, bytes, 30, 3);
  }

  void insert(long id, String name, byte[] content, Long expiry) {
    jdbc.update(
        "insert into mblob (id, name, content, created_date, expire_after_seconds) values (?, ?, ?, ?, ?)",
        id,
        name,
        content,
        Timestamp.from(Instant.parse("2025-01-01T00:00:00Z")),
        expiry);
  }

  static byte[] bytes(String value) {
    return value.getBytes(StandardCharsets.UTF_8);
  }
}
