package com.box.l10n.mojito.service.blobstorage.migration;

import static org.junit.Assert.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

import com.box.l10n.mojito.quartz.QuartzSchedulerManager;
import com.box.l10n.mojito.service.blobstorage.Retention;
import com.box.l10n.mojito.service.blobstorage.azure.AzureBlobStorage;
import com.box.l10n.mojito.service.blobstorage.azure.AzureBlobStorage.MigrationBlob;
import com.box.l10n.mojito.service.blobstorage.migration.BlobMigrationMaintenanceFence.Lease;
import com.box.l10n.mojito.service.blobstorage.migration.BlobMigrationPromotionStore.Run;
import java.nio.charset.StandardCharsets;
import java.sql.Timestamp;
import java.time.Duration;
import java.time.Instant;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.atomic.AtomicBoolean;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.springframework.beans.factory.ObjectProvider;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.ClassPathResource;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabase;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseBuilder;
import org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseType;
import org.springframework.jdbc.datasource.init.ResourceDatabasePopulator;
import org.springframework.transaction.support.TransactionSynchronizationManager;

public class BlobMigrationPromotionServiceTest {
  EmbeddedDatabase database;
  JdbcTemplate jdbc;
  BlobMigrationStore snapshots;
  BlobMigrationPromotionStore promotions;
  BlobMigrationProperties properties;
  AzureBlobStorage azure;
  BlobMigrationService snapshotService;
  BlobMigrationPromotionService service;
  BlobMigrationMaintenanceFence fence;
  Lease lease;
  Map<String, byte[]> backup;
  Map<String, MigrationBlob> canonical;

  @Before
  @SuppressWarnings("unchecked")
  public void setup() throws Exception {
    database =
        new EmbeddedDatabaseBuilder()
            .generateUniqueName(true)
            .setType(EmbeddedDatabaseType.HSQL)
            .build();
    jdbc = new JdbcTemplate(database);
    jdbc.execute("set database sql syntax mys true");
    jdbc.execute(
        "create table mblob (id bigint generated by default as identity primary key, name varchar(255), content varbinary(1048576), created_date timestamp(6), expire_after_seconds bigint)");
    String ddl =
        new ClassPathResource("db/migration/V121__MBlob_Migration.sql")
            .getContentAsString(StandardCharsets.UTF_8)
            .replace("datetime(6)", "timestamp(6)")
            .replace(" bit ", " boolean ");
    new ResourceDatabasePopulator(new ByteArrayResource(ddl.getBytes(StandardCharsets.UTF_8)))
        .execute(database);
    var transactions = new DataSourceTransactionManager(database);
    snapshots = new BlobMigrationStore(jdbc, transactions);
    promotions = new BlobMigrationPromotionStore(jdbc, transactions, snapshots);
    properties = new BlobMigrationProperties();
    properties.setEnabled(true);
    properties.setPromotionEnabled(true);
    azure = mock(AzureBlobStorage.class);
    ObjectProvider<AzureBlobStorage> provider = mock(ObjectProvider.class);
    when(provider.getIfAvailable()).thenReturn(azure);
    when(azure.getTargetDescription(anyString()))
        .thenAnswer(
            call -> "https://example.blob.core.windows.net/container/root/" + call.getArgument(0));
    snapshotService =
        new BlobMigrationService(
            snapshots, properties, provider, mock(QuartzSchedulerManager.class));
    fence = mock(BlobMigrationMaintenanceFence.class);
    lease = mock(Lease.class);
    when(lease.manifestSha256()).thenReturn("a".repeat(64));
    when(lease.validUntil()).thenReturn(Instant.now().plusSeconds(300));
    when(fence.verify(anyString(), anyString(), anyString(), nullable(String.class)))
        .thenReturn(lease);
    service = new BlobMigrationPromotionService(snapshots, promotions, properties, fence, provider);
    backup = new HashMap<>();
    canonical = new HashMap<>();
    when(azure.createSnapshotIfAbsent(anyString(), any(byte[].class)))
        .thenAnswer(
            call ->
                backup.putIfAbsent(call.getArgument(0), ((byte[]) call.getArgument(1)).clone())
                    == null);
    when(azure.getSnapshotBytes(anyString(), anyInt()))
        .thenAnswer(
            call -> {
              assertFalse(TransactionSynchronizationManager.isActualTransactionActive());
              byte[] result = backup.get(call.getArgument(0));
              if (result == null || result.length != (int) call.getArgument(1))
                throw new AzureBlobStorage.SnapshotVerificationException();
              return result.clone();
            });
    when(azure.inspectCanonicalBlobForMigration(anyString(), anyInt()))
        .thenAnswer(
            call -> {
              assertFalse(TransactionSynchronizationManager.isActualTransactionActive());
              return Optional.ofNullable(canonical.get(call.getArgument(0)));
            });
    when(azure.createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class)))
        .thenAnswer(
            call -> {
              assertFalse(TransactionSynchronizationManager.isActualTransactionActive());
              String name = call.getArgument(0);
              byte[] bytes = ((byte[]) call.getArgument(1)).clone();
              return canonical.putIfAbsent(
                      name,
                      new MigrationBlob(
                          bytes.length, bytes, "etag-" + name, call.getArgument(2).toString()))
                  == null;
            });
  }

  @After
  public void close() {
    if (database != null) database.shutdown();
  }

  @Test
  public void defaultDisabledAndSnapshotJobCannotPromote() {
    assertFalse(new BlobMigrationProperties().isPromotionEnabled());
    properties.setPromotionEnabled(false);
    assertThrows(
        IllegalStateException.class,
        () -> service.create(new BlobMigrationPromotionService.CreateRequest("x", "fence")));
    assertThrows(IllegalStateException.class, () -> service.runBatch("x"));
    insert(1, "clob_storage_ws/a", "a", null);
    snapshot(10, 100);
    verifyNoInteractions(fence);
    verify(azure, never())
        .createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class));
  }

  @Test
  public void promotesThenSeparatelyReconcilesAllRowsWithRetentionAndNoSourceDeletes() {
    insert(1, "clob_storage_ws/permanent", "one", null);
    insert(2, "clob_storage_ws/temporary", "two", 30L * 86400);
    Instant created = Instant.now().minusSeconds(10L * 86400);
    jdbc.update("update mblob set created_date = ? where id = 2", Timestamp.from(created));
    String source = snapshot(10, 100);
    Run run = create(source);
    assertEquals("READY", run.status());
    Run copied = service.runBatch(run.id());
    assertEquals("RECONCILE", copied.phase());
    assertEquals(0, copied.reconciledCount());
    assertThrows(IllegalStateException.class, () -> service.readiness(run.id()));
    Run complete = service.runBatch(run.id());
    assertEquals("RECONCILED", complete.status());
    assertEquals(2, complete.reconciledCount());
    assertEquals(1, complete.canonicalCount());
    assertEquals(1, complete.retainedCount());
    assertEquals(3, complete.retainedBytes());
    assertEquals("PERMANENT", canonical.get("clob_storage_ws/permanent").retention());
    assertFalse(canonical.containsKey("clob_storage_ws/temporary"));
    assertEquals("RETAIN_TEMPORARY_LIFETIME", promotions.item(run.id(), 2).disposition());
    assertEquals(Long.valueOf(30L * 86400), promotions.item(run.id(), 2).sourceExpireSeconds());
    assertEquals(
        snapshots.metadata(2).createdDate(), promotions.item(run.id(), 2).sourceCreatedDate());
    verify(azure, never())
        .inspectCanonicalBlobForMigration(eq("clob_storage_ws/temporary"), anyInt());
    assertArrayEquals(bytes("one"), canonical.get("clob_storage_ws/permanent").content());
    assertEquals(2, (long) jdbc.queryForObject("select count(*) from mblob", Long.class));
    assertNotNull(service.readiness(run.id()).validUntil());
    verify(fence, atLeastOnce())
        .verify(eq(source), eq("maintenance-fence"), eq(run.destinationRoot()), eq("a".repeat(64)));
  }

  @Test
  public void existingIdenticalCanonicalIsVerifiedWithoutRewrite() {
    insert(1, "clob_storage_ws/a", "a", null);
    String source = snapshot(10, 100);
    canonical.put("clob_storage_ws/a", remote("a", "PERMANENT", "existing"));
    Run run = create(source);
    complete(run.id());
    assertEquals(1, promotions.get(run.id()).canonicalCount());
    assertEquals("existing", promotions.item(run.id(), 1).canonicalEtag());
    verify(azure, never())
        .createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class));
  }

  @Test
  public void conflictsChangedSourcesUnknownControlsAndPreFenceDeltaRemainInReplacement() {
    insert(1, "clob_storage_ws/conflict", "one", null);
    insert(2, "clob_storage_ws/retention", "two", null);
    insert(3, "unknown/keep", "three", null);
    insert(4, "ai_review_execution/v1/capacity", "four", null);
    insert(5, "clob_storage_ws/changed", "old", null);
    String source = snapshot(10, 100);
    jdbc.update("update mblob set content = ? where id = 5", bytes("new"));
    insert(6, "clob_storage_ws/delta", "six", null);
    canonical.put("clob_storage_ws/conflict", remote("bad", "PERMANENT", "conflict"));
    canonical.put("clob_storage_ws/retention", remote("two", "MIN_1_DAY", "temporary"));
    Run run = create(source);
    complete(run.id());
    Run result = promotions.get(run.id());
    assertEquals(6, result.reconciledCount());
    assertEquals(6, result.retainedCount());
    assertEquals(0, result.canonicalCount());
    assertEquals(21, result.retainedBytes());
    assertEquals(
        List.of(
            "RETAIN_CANONICAL_CONFLICT",
            "RETAIN_RETENTION_CONFLICT",
            "RETAIN_PRESERVED_UNKNOWN",
            "RETAIN_PRESERVED_CONTROL",
            "RETAIN_SOURCE_CHANGED",
            "RETAIN_DELTA"),
        promotions.items(run.id(), 0, 10).stream()
            .map(BlobMigrationPromotionStore.Item::disposition)
            .toList());
    assertArrayEquals(bytes("bad"), canonical.get("clob_storage_ws/conflict").content());
    assertEquals(6, (long) jdbc.queryForObject("select count(*) from mblob", Long.class));
    assertTrue(promotions.hasConflicts(run.id()));
    assertThrows(IllegalStateException.class, () -> service.readiness(run.id()));
    verify(azure, never())
        .createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class));
  }

  @Test
  public void contentAndRetentionConflictsEachBlockReadinessUntilFreshPromotionResolvesThem() {
    insert(1, "clob_storage_ws/a", "one", null);
    String snapshot = snapshot(10, 100);
    for (MigrationBlob conflict :
        List.of(remote("bad", "PERMANENT", "content"), remote("one", "MIN_1_DAY", "retention"))) {
      canonical.put("clob_storage_ws/a", conflict);
      Run blocked = create(snapshot);
      complete(blocked.id());
      assertTrue(promotions.hasConflicts(blocked.id()));
      assertThrows(IllegalStateException.class, () -> service.readiness(blocked.id()));
    }
    canonical.put("clob_storage_ws/a", remote("one", "PERMANENT", "resolved"));
    Run resolved = create(snapshot);
    complete(resolved.id());
    assertFalse(promotions.hasConflicts(resolved.id()));
    assertNotNull(service.readiness(resolved.id()));
  }

  @Test
  @SuppressWarnings("unchecked")
  public void claimantReloadsPhaseWhenAnotherWorkerProgressesAfterItsPreflight() {
    insert(1, "clob_storage_ws/a", "one", null);
    Run run = create(snapshot(10, 100));
    BlobMigrationPromotionStore contended = spy(promotions);
    doAnswer(
            call -> {
              assertEquals("RECONCILE", service.runBatch(run.id()).phase());
              return promotions.claim(run.id(), call.getArgument(1));
            })
        .when(contended)
        .claim(eq(run.id()), anyInt());
    ObjectProvider<AzureBlobStorage> provider = mock(ObjectProvider.class);
    when(provider.getIfAvailable()).thenReturn(azure);
    var claimant =
        new BlobMigrationPromotionService(snapshots, contended, properties, fence, provider);
    Run completed = claimant.runBatch(run.id());
    assertEquals("RECONCILED", completed.status());
    assertEquals(1, completed.reconciliationCursor());
    assertEquals(1, completed.reconciledCount());
    assertTrue(promotions.item(run.id(), 1).reconciled());
    verify(azure, times(3)).inspectCanonicalBlobForMigration(eq("clob_storage_ws/a"), anyInt());
  }

  @Test
  public void storeCannotAdvanceReconciliationWithUnverifiedItemOrPublishEarlyCompletion() {
    insert(1, "clob_storage_ws/a", "one", null);
    Run run = create(snapshot(10, 100));
    assertEquals("RECONCILE", service.runBatch(run.id()).phase());
    String token = promotions.claim(run.id(), 120);
    var unverified = promotions.item(run.id(), 1);
    assertFalse(unverified.reconciled());
    assertThrows(
        IllegalStateException.class, () -> promotions.record(run.id(), token, unverified, true));
    assertThrows(
        IllegalStateException.class,
        () -> promotions.release(run.id(), token, "RECONCILED", null, lease.validUntil()));
    assertEquals(0, promotions.get(run.id()).reconciliationCursor());
    assertEquals(0, promotions.get(run.id()).reconciledCount());
  }

  @Test
  public void disappearingNonMaximumPromotedSourceBlocksCompletionAndHistoricalReadiness() {
    insert(1, "clob_storage_ws/a", "one", null);
    insert(2, "clob_storage_ws/b", "two", null);
    Run run = create(snapshot(10, 100));
    assertEquals("RECONCILE", service.runBatch(run.id()).phase());
    jdbc.update("delete from mblob where id = 1");
    assertEquals(run.sourceHighWaterId(), snapshots.maxSourceId());
    assertThrows(IllegalStateException.class, () -> service.runBatch(run.id()));
    assertEquals("PAUSED", promotions.get(run.id()).status());
    assertEquals(2, promotions.get(run.id()).reconciliationCursor());
    assertTrue(promotions.hasUnreconciledCanonical(run.id()));
    assertFalse(promotions.item(run.id(), 1).reconciled());
    assertTrue(promotions.item(run.id(), 2).reconciled());
    // A historical/incorrect completion marker must not bypass the same readiness invariant.
    jdbc.update(
        "update mblob_migration_promotion set status = 'RECONCILED', phase = 'COMPLETE', last_error = null where id = ?",
        run.id());
    assertThrows(IllegalStateException.class, () -> service.readiness(run.id()));
    assertEquals(1, (long) jdbc.queryForObject("select count(*) from mblob", Long.class));
  }

  @Test
  public void boundedBatchesResumeThroughPromotionAndFullSourceReconciliation() {
    insert(1, "clob_storage_ws/a", "one", null);
    insert(2, "clob_storage_ws/b", "two", null);
    String source = snapshot(10, 5);
    Run run = create(source);
    assertEquals(1, service.runBatch(run.id()).promotionCursor());
    assertEquals("RECONCILE", service.runBatch(run.id()).phase());
    assertEquals(1, service.runBatch(run.id()).reconciliationCursor());
    assertEquals("RECONCILED", service.runBatch(run.id()).status());
    assertEquals(2, promotions.get(run.id()).canonicalCount());
    verify(azure, times(2))
        .createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class));
  }

  @Test
  public void snapshotCorruptionPausesWithoutAdvancingAndRetryDoesNotSkipFailure() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    var evidence = snapshots.evidence(source, 0, 10).getFirst();
    backup.put(evidence.snapshotName(), bytes("bad"));
    Run run = create(source);
    assertThrows(
        AzureBlobStorage.SnapshotVerificationException.class, () -> service.runBatch(run.id()));
    assertEquals("PAUSED", promotions.get(run.id()).status());
    assertEquals(0, promotions.get(run.id()).promotionCursor());
    assertTrue(canonical.isEmpty());
    backup.put(evidence.snapshotName(), bytes("one"));
    complete(run.id());
    assertEquals(1, promotions.get(run.id()).canonicalCount());
  }

  @Test
  public void sourceMutationDuringCanonicalCopyInvalidatesFenceAndReadiness() {
    insert(1, "clob_storage_ws/a", "old", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    when(azure.createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class)))
        .thenAnswer(
            call -> {
              canonical.put(call.getArgument(0), remote("old", "PERMANENT", "copied"));
              jdbc.update("update mblob set content = ? where id = 1", bytes("new"));
              return true;
            });
    assertThrows(
        BlobMigrationPromotionService.FenceInvariantViolation.class,
        () -> service.runBatch(run.id()));
    assertEquals("PAUSED", promotions.get(run.id()).status());
    assertEquals(0, promotions.get(run.id()).promotionCursor());
    assertArrayEquals(
        bytes("new"), jdbc.queryForObject("select content from mblob where id = 1", byte[].class));
    assertThrows(IllegalStateException.class, () -> service.readiness(run.id()));
  }

  @Test
  public void newSourceRowWhileFenceHeldBlocksCopyAndFinalReadiness() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    insert(2, "clob_storage_ws/late", "late", null);
    assertThrows(
        BlobMigrationPromotionService.FenceInvariantViolation.class,
        () -> service.runBatch(run.id()));
    assertEquals("PAUSED", promotions.get(run.id()).status());
    assertTrue(canonical.isEmpty());
  }

  @Test
  public void finalCanonicalMismatchCannotTurnIntoRetainedSuccessOnRetry() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    service.runBatch(run.id());
    MigrationBlob good = canonical.get("clob_storage_ws/a");
    canonical.put("clob_storage_ws/a", remote("bad", "PERMANENT", "changed"));
    for (int retry = 0; retry < 2; retry++) {
      assertThrows(
          AzureBlobStorage.SnapshotVerificationException.class, () -> service.runBatch(run.id()));
      assertEquals(0, promotions.get(run.id()).reconciliationCursor());
      assertEquals(0, promotions.get(run.id()).retainedCount());
    }
    canonical.put("clob_storage_ws/a", good);
    assertEquals("RECONCILED", service.runBatch(run.id()).status());
    assertEquals(1, promotions.get(run.id()).canonicalCount());
  }

  @Test
  public void pauseFencesStaleWorkerAfterCreateAndResumeVerifiesExistingCopy() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    AtomicBoolean pause = new AtomicBoolean(true);
    when(azure.createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class)))
        .thenAnswer(
            call -> {
              boolean created =
                  canonical.putIfAbsent(call.getArgument(0), remote("one", "PERMANENT", "first"))
                      == null;
              if (pause.getAndSet(false)) promotions.pause(run.id());
              return created;
            });
    assertThrows(BlobMigrationStore.LeaseLost.class, () -> service.runBatch(run.id()));
    assertEquals(0, promotions.get(run.id()).promotionCursor());
    assertNull(promotions.item(run.id(), 1));
    complete(run.id());
    assertEquals(1, promotions.get(run.id()).canonicalCount());
    verify(azure, times(1))
        .createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class));
  }

  @Test
  public void insufficientExternalLeaseMustRenewBeforeAnyCanonicalOperation() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    doThrow(new IllegalStateException("expired"))
        .when(lease)
        .requireRemaining(Duration.ofSeconds(95));
    when(fence.verify(
            eq(source), eq(run.fenceId()), eq(run.destinationRoot()), eq(run.manifestSha256())))
        .thenReturn(lease)
        .thenThrow(new IllegalStateException("fence revoked"));
    assertThrows(IllegalStateException.class, () -> service.runBatch(run.id()));
    assertEquals("PAUSED", promotions.get(run.id()).status());
    verify(azure, never()).inspectCanonicalBlobForMigration(anyString(), anyInt());
    verify(azure, never())
        .createCanonicalBlobForMigrationIfAbsent(
            anyString(), any(byte[].class), any(Retention.class));
  }

  @Test
  public void finalExternalVerificationFailureBlocksPublicationUntilSameFenceReturns() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    service.runBatch(run.id());
    when(fence.verify(
            eq(source), eq(run.fenceId()), eq(run.destinationRoot()), eq(run.manifestSha256())))
        .thenReturn(lease)
        .thenThrow(new IllegalStateException("revoked"));
    assertThrows(IllegalStateException.class, () -> service.runBatch(run.id()));
    assertEquals("PAUSED", promotions.get(run.id()).status());
    assertEquals(1, promotions.get(run.id()).reconciledCount());
    assertThrows(IllegalStateException.class, () -> service.readiness(run.id()));
    when(fence.verify(anyString(), anyString(), anyString(), nullable(String.class)))
        .thenReturn(lease);
    assertEquals("RECONCILED", service.runBatch(run.id()).status());
  }

  @Test
  public void destinationPinAndReadinessRequireCurrentExternalProof() {
    insert(1, "clob_storage_ws/a", "one", null);
    String source = snapshot(10, 100);
    Run run = create(source);
    complete(run.id());
    when(fence.verify(
            eq(source), eq(run.fenceId()), eq(run.destinationRoot()), eq(run.manifestSha256())))
        .thenThrow(new IllegalStateException("manifest changed"));
    assertThrows(IllegalStateException.class, () -> service.readiness(run.id()));
    when(azure.getTargetDescription(anyString())).thenReturn("https://elsewhere");
    assertThrows(
        IllegalStateException.class,
        () ->
            service.create(
                new BlobMigrationPromotionService.CreateRequest(source, "another-fence")));
  }

  @Test
  public void verifierRunsAtBatchBoundariesInsteadOfPerObject() {
    for (int i = 1; i <= 10; i++) insert(i, "clob_storage_ws/" + i, "data", null);
    String source = snapshot(100, 1000);
    Run run = create(source);
    complete(run.id());
    verify(fence, times(5)).verify(anyString(), anyString(), anyString(), nullable(String.class));
    assertEquals(10, promotions.get(run.id()).canonicalCount());
  }

  @Test
  public void databaseLeaseClaimRejectsDuplicateWorkerAndOldTokenAfterTakeover() {
    String source = snapshot(10, 100);
    Run run = create(source);
    String old = promotions.claim(run.id(), 120);
    assertNull(promotions.claim(run.id(), 120));
    jdbc.update(
        "update mblob_migration_promotion set lease_until = ? where id = ?",
        Timestamp.from(Instant.now().minusSeconds(10)),
        run.id());
    String next = promotions.claim(run.id(), 120);
    assertNotNull(next);
    assertNotEquals(old, next);
    assertThrows(BlobMigrationStore.LeaseLost.class, () -> promotions.renew(run.id(), old, 120));
    assertThrows(
        BlobMigrationStore.LeaseLost.class,
        () -> promotions.release(run.id(), old, "RECONCILED", null, lease.validUntil()));
  }

  String snapshot(int rows, long budget) {
    var run =
        snapshotService.create(
            new BlobMigrationService.CreateRequest(
                List.of("clob_storage_ws"), rows, budget, 30, 3));
    snapshots.request(run.id(), true);
    for (int i = 0; i < 100 && !snapshots.get(run.id()).status().startsWith("SNAPSHOT_"); i++)
      snapshotService.runBatch(run.id());
    assertEquals("SNAPSHOT_COMPLETE", snapshots.get(run.id()).status());
    return run.id();
  }

  Run create(String snapshot) {
    return service.create(
        new BlobMigrationPromotionService.CreateRequest(snapshot, "maintenance-fence"));
  }

  void complete(String id) {
    for (int i = 0; i < 100 && !"RECONCILED".equals(promotions.get(id).status()); i++)
      service.runBatch(id);
    assertEquals("RECONCILED", promotions.get(id).status());
  }

  void insert(long id, String name, String content, Long expiry) {
    jdbc.update(
        "insert into mblob (id,name,content,created_date,expire_after_seconds) values (?,?,?,?,?)",
        id,
        name,
        bytes(content),
        Timestamp.from(Instant.parse("2025-01-01T00:00:00Z")),
        expiry);
  }

  static byte[] bytes(String value) {
    return value.getBytes(StandardCharsets.UTF_8);
  }

  static MigrationBlob remote(String content, String retention, String etag) {
    return new MigrationBlob(bytes(content).length, bytes(content), etag, retention);
  }
}
