export const REPLACEMENT_TEXT_MAX_LENGTH = 4000;
export const AI_REPLACEMENT_RULE_MAX_LENGTH = 4000;
export const AI_TERM_MAX_COUNT = 100;
export const AI_TERM_MAX_LENGTH = 256;
export const REPLACEMENT_GENERATION_LIMIT_MIN = 1;
export const REPLACEMENT_SEARCH_SCOPE_LIST_MAX_COUNT = 1000;
export const REPLACEMENT_GENERATION_LIMIT_MAX = REPLACEMENT_SEARCH_SCOPE_LIST_MAX_COUNT;
